       ORG          0
       MOV.I  $    33, $  1031     
       MOV.I  $    31, <    -1     
       MOV.I  $    28, <    -2     
       MOV.I  $    30, $  2029     
       MOV.I  $    28, <    -1     
       MOV.I  $    25, <    -2     
       MOV.I  $    27, $  3029     
       MOV.I  $    25, <    -1     
       MOV.I  $    22, <    -2     
       MOV.I  $    24, $ -3973     
       MOV.I  $    22, <    -1     
       MOV.I  $    19, <    -2     
       MOV.I  $    21, $ -2973     
       MOV.I  $    19, <    -1     
       MOV.I  $    16, <    -2     
       MOV.I  $    18, $ -1975     
       MOV.I  $    16, <    -1     
       MOV.I  $    13, <    -2     
       MOV.I  $    15, $  -975     
       MOV.I  $    13, <    -1     
       MOV.I  $    10, <    -2     
       SPL.B  @   -21, $     0     
       SPL.B  @   -19, $     0     
       SPL.B  @   -17, $     0     
       SPL.B  @   -15, $     0     
       SPL.B  @   -13, $     0     
       SPL.B  @   -11, $     0     
       SPL.B  @    -9, $     0     
       JMP.B  $     2, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     0, <    -1     
       MOV.I  $    -2, <    -2     
       MOV.I  $    -3, <    -3     
       JMP.B  $    -3, <    -4     
       END
