       ORG        110
       DAT.F  $   -53, $    53     
       DAT.F  $   -52, $    52     
       DAT.F  $   -51, $    51     
       DAT.F  $   -50, $    50     
       DAT.F  $   -49, $    49     
       DAT.F  $   -48, $    48     
       DAT.F  $   -47, $    47     
       DAT.F  $   -46, $    46     
       DAT.F  $   -45, $    45     
       DAT.F  $   -44, $    44     
       DAT.F  $   -43, $    43     
       DAT.F  $   -42, $    42     
       DAT.F  $   -41, $    41     
       DAT.F  $   -40, $    40     
       DAT.F  $   -39, $    39     
       DAT.F  $   -38, $    38     
       DAT.F  $   -37, $    37     
       DAT.F  $   -36, $    36     
       DAT.F  $   -35, $    35     
       DAT.F  $   -34, $    34     
       DAT.F  $   -33, $    33     
       DAT.F  $   -32, $    32     
       DAT.F  $   -31, $    31     
       DAT.F  $   -30, $    30     
       DAT.F  $   -29, $    29     
       DAT.F  $   -28, $    28     
       DAT.F  $   -27, $    27     
       DAT.F  $   -26, $    26     
       DAT.F  $   -25, $    25     
       DAT.F  $   -24, $    24     
       DAT.F  $   -23, $    23     
       DAT.F  $   -22, $    22     
       DAT.F  $   -21, $    21     
       DAT.F  $   -20, $    20     
       DAT.F  $   -19, $    19     
       DAT.F  $   -18, $    18     
       DAT.F  $   -17, $    17     
       DAT.F  $   -16, $    16     
       DAT.F  $   -15, $    15     
       DAT.F  $   -14, $    14     
       DAT.F  $   -13, $    13     
       DAT.F  $   -12, $    12     
       DAT.F  $   -11, $    11     
       DAT.F  $   -10, $    10     
       DAT.F  $    -9, $     9     
       DAT.F  $    -8, $     8     
       DAT.F  $    -7, $     7     
       DAT.F  $    -6, $     6     
       DAT.F  $    -5, $     5     
       DAT.F  $    -4, $     4     
       DAT.F  $    -3, $     3     
       MOV.I  $     3, >     3     
       MOV.I  $     2, {     2     
       DJN.B  $    -2, #   -53     
       DAT.F  $   -51, $    51     
       DAT.F  $     0, $     0     
       DAT.F  $    -3, $     2     
       DAT.F  $    -4, $     3     
       DAT.F  $    -5, $     4     
       DAT.F  $    -6, $     5     
       DAT.F  $    -7, $     6     
       DAT.F  $    -8, $     7     
       DAT.F  $    -9, $     8     
       DAT.F  $   -10, $     9     
       DAT.F  $   -11, $    10     
       DAT.F  $   -12, $    11     
       DAT.F  $   -13, $    12     
       DAT.F  $   -14, $    13     
       DAT.F  $   -15, $    14     
       DAT.F  $   -16, $    15     
       DAT.F  $   -17, $    16     
       DAT.F  $   -18, $    17     
       DAT.F  $   -19, $    18     
       DAT.F  $   -20, $    19     
       DAT.F  $   -21, $    20     
       DAT.F  $   -22, $    21     
       DAT.F  $   -23, $    22     
       DAT.F  $   -24, $    23     
       DAT.F  $   -25, $    24     
       DAT.F  $   -26, $    25     
       DAT.F  $   -27, $    26     
       DAT.F  $   -28, $    27     
       DAT.F  $   -29, $    28     
       DAT.F  $   -30, $    29     
       DAT.F  $   -31, $    30     
       DAT.F  $   -32, $    31     
       DAT.F  $   -33, $    32     
       DAT.F  $   -34, $    33     
       DAT.F  $   -35, $    34     
       DAT.F  $   -36, $    35     
       DAT.F  $   -37, $    36     
       DAT.F  $   -38, $    37     
       DAT.F  $   -39, $    38     
       DAT.F  $   -40, $    39     
       DAT.F  $   -41, $    40     
       DAT.F  $   -42, $    41     
       DAT.F  $   -43, $    42     
       DAT.F  $   -44, $    43     
       DAT.F  $   -45, $    44     
       DAT.F  $   -46, $    45     
       DAT.F  $   -47, $    46     
       DAT.F  $   -48, $    47     
       DAT.F  $   -49, $    48     
       DAT.F  $   -50, $    49     
       DAT.F  $   -51, $    50     
       DAT.F  $   -52, $    51     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       STP.AB #     5, #     5     
       JMP.B  $     6, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  #   -15, #    15     
       ADD.F  $    -1, $     1     
       SNE.I  $  -301, $   267     
       JMP.B  $    -2, $     0     
       MOV.I  $    -2, $    76     
       SEQ.I  $    45, *    -3     
       JMP.B  $    54, $     0     
       MOV.I  @    -5, $    72     
       ADD.B  $    71, $    -6     
       MOV.I  @    -7, $    72     
       NOP.F  $     0, $     0     
       NOP.F  $     0, $     0     
       MOV.I  @   -10, $    67     
       SNE.I  $    66, $    68     
       JMP.B  $    51, $     0     
       SUB.AB #     1, $   -13     
       MOV.I  @   -14, $    65     
       SEQ.I  $    64, $    65     
       JMP.B  $    47, $     0     
       ADD.AB #     3, $   -17     
       MOV.I  $    35, @   -18     
       SUB.AB #    10, $   -19     
       MOV.I  $    28, @   -20     
       MOV.AB #    26, $     3     
       MOV.I  $    35, <   -22     
       SUB.A  #     1, $    -1     
       DJN.B  $    -2, #    26     
       MOV.I  $   -25, $    52     
       SUB.AB #    32, $    51     
       MOV.BA @    -1, $    26     
       MOV.I  $     3, $   -90     
       ADD.AB #     2, $   -29     
       JMP.B  @   -30, $     0     
       JMP.B  $   115, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       ADD.AB #   135, $     1     
       SNE.I  $    -2, $  1003     
       JMZ.B  $    -2, $    -4     
       JMP.B  $     2, $     0     
       DAT.F  $     0, $     0     
       MOV.BA $    -4, $     8     
       MUL.A  #    -1, $     7     
       ADD.A  #    18, $     6     
       JMP.B  $     2, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, @    -9     
       JMZ.B  $   -11, $   -13     
       JMP.B  $     3, $     0     
       JMP.B  $    30, $    30     
       DAT.F  $     0, $     0     
       MOV.I  $     4, $   -17     
       MOV.I  $     7, $   -17     
       MOV.I  $     5, $     2     
       JMP.B  $     2, }    18     
       JMP.B  $     0, $     0     
       MOV.I  $     4, $    14     
       JMP.B  @    -5, <     5     
       JMP.B  $   -21, }    19     
       JMN.B  $     0, $    33     
       MOV.I  *   -58, $    19     
       ADD.A  $   -59, $    18     
       MUL.AB #    -1, $    17     
       MOV.AB $    16, $   -61     
       JMP.B  $   -55, $     0     
       MOV.BA $   -63, $    11     
       MOV.B  $   -64, $    10     
       SUB.F  $    10, $     9     
       MUL.A  #    -1, $     8     
       MOV.I  $     7, @     7     
       ADD.AB #     1, $     6     
       MOV.I  $     7, >     5     
       MOV.I  $     6, >     4     
       MOV.I  $     5, >     3     
       MOV.I  $     6, $   -72     
       JMP.B  $   -74, $     0     
       JMP.B  $     0, $  3500     
       DAT.F  #    54, #    75     
       JMP.B  $    -1, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     2, {     2     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       PIN        103
       END
