       ORG         45
       SPL.B  #   132, $   132     
       ADD.F  $    -1, $     1     
       CMP.I  $    65, $    -1     
       SLT.AB #    20, $    -1     
       DJN.F  $    -3, < -2900     
       MOV.I  $     7, @    -3     
       MOV.I  $    -6, <    -4     
       MOV.I  $    -7, <    -5     
       SUB.F  $     5, $    -6     
       JMN.B  $    -7, $    -8     
       ADD.A  #   382, $     4     
       MOV.I  @    -1, {     3     
       JMP.B  $    -2, $     0     
       DAT.F  <   -66, <   -68     
       SPL.B  #     2, #     3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.AB #     0, #     0     
       LDP.A  #   111, $     5     
       SEQ.AB #     1, $    -2     
       ADD.A  #     1, $     3     
       MOD.A  #     2, $     2     
       STP.AB $     1, #   111     
       JMP.B  @     0, $   -50     
       DAT.F  $     0, $    19     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  <  -445, <  -446     
       SPL.B  #   445, <  -445     
       SPL.B  #     0, <  -446     
       MOV.I  {   444, $  -443     
       ADD.F  $    -3, $    -1     
       DJN.F  $    -2, < -3167     
       MOV.I  $    33, <   -20     
       DAT.F  #     0, # -1333     
       MOV.I  {    -1, <    -1     
       MOV.I  {    -2, <    -2     
       MOV.I  {    -3, <    -3     
       MOV.I  {    -4, <    -4     
       MOV.I  {    -5, <    -5     
       MOV.I  {    -6, <    -6     
       MOV.I  $   -14, $ -1309     
       MOV.I  $   -15, $ -1309     
       SPL.B  @    -9, <  4000     
       JMP.B  $    11, <  3987     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       DAT.F  $     1, $     1     
       SPL.B  $     1, #     0     
       SPL.B  $     1, #     0     
       SPL.B  <     0, #     7     
       DJN.A  @     5, #     0     
       MOV.I  #     0, $  2667     
       JMP.B  $  2668, $     1     
       JMP.B  $ -2667, $  2666     
       JMP.B  $    -2, $ -2669     
       JMP.B  $  2663, $    -4     
       END
