       ORG         22
       JMP.B  @  -465, $   474     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  <  2667, $     9     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #  -474, #   474     
       MOV.I  @     0, @   -19     
       ADD.F  $    -2, $   -20     
       JMP.B  $    -2, $     0     
       SPL.B  $    -4, $     0     
       JMP.B  $    10, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, {    -4     
       MOV.I  $     3, >    -5     
       DJN.F  $    -1, >    -6     
       DAT.F  $     0, $     0     
       DAT.F  >  2667, $     9     
       END
