       ORG          0
       SPL.B  $     2, >   -80     
       SPL.B  $     1, }   -86     
       SPL.B  $     1, <   -92     
       SPL.B  $    41, {   -98     
       SPL.B  @     0, >   838     
       MOV.I  }    -1, >    -1     
       MOV.I  $    28, >  3530     
       MOV.I  $    27, >  1955     
       MOV.I  {    -4, {     1     
       JMZ.A  *  -736, *     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  >  2667, > -2666     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     0, > -1377     
       MOV.I  }    -1, >    -1     
       MOV.I  $   -12, >  1275     
       MOV.I  $   -13, > -2377     
       MOV.I  {    -4, {     1     
       JMZ.A  *  2972, *     0     
       END
