       ORG         27
       DAT.F  $     0, $    21     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     1, $    14     
       SPL.B  #    96, $    14     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #    18, $    18     
       MOV.I  *    -5, >    -9     
       MOV.I  *    -6, >   -10     
       DJN.F  $    -2, }    -6     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       ADD.F  $   -19, $     2     
       MOV.I  $    10, *     1     
       SNE.I  } -3799, >   185     
       DJN.F  $    -3, @    -1     
       ADD.B  $    -2, $   -31     
       JMP.B  $   -24, <  2533     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $  3991, {     1     
       END
