       ORG          0
       ADD.F  $    13, $     3     
       SNE.I  *     2, @     2     
       ADD.F  $    11, $     1     
       SNE.I  $  3517, $  3507     
       DJN.F  $    -4, < -1488     
       ADD.AB #   -15, $    -2     
       MOV.I  <    67, <    -3     
       MOV.I  <    66, <    -4     
       MOV.I  <    65, <    -5     
       DJN.B  $    -2, #     4     
       ADD.AB #     5, $    -7     
       SPL.B  @    -8, $     0     
       MOV.I  $    62, $    -9     
       DAT.F  #  1605, <  1605     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $ -3949, $    18     
       JMP.B  $ -3949, $    18     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  $  -400, <  -200     
       SPL.B  # -3319, $    18     
       MOV.I  @     2, >    -6     
       MOV.I  $    -6, }    -7     
       DJN.B  $    -2, {    -3     
       DAT.F  $     0, $     0     
       END
