       ORG         91
       STP.AB #    12, #   230     
       STP.AB #    17, #   460     
       SPL.B  $     1, <  3555     
       SPL.B  $     1, < -2665     
       SPL.B  $     1, <  2363     
       MOV.I  {    14, {     1     
       SPL.B  $ -1867, > -2253     
       MOV.I  {     3, {     1     
       DJN.F  $ -3878, > -3416     
       DAT.F  $     0, $     0     
       SPL.B  @     8, }  3218     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, } -2830     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, }   851     
       MOV.I  }    -1, >    -1     
       MOV.I  #  1138, <     1     
       DJN.B  $    -2, <   973     
       DAT.F  $     0, $     0     
       SPL.B  @     8, }  2044     
       MOV.I  }    -1, >    -1     
       SPL.B  #     0, $     0     
       MOV.I  $     3, >     2     
       ADD.X  $     3, $     1     
       JMP.B  $ -1142, > -3103     
       DAT.F  >     1, }     1     
       MOV.I  # -3098, $  1143     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  >   -87, > -1375     
       MOV.I  $    25, $ -3405     
       SPL.B  }     2, }  2487     
       SPL.B  $     1, }   418     
       SPL.B  $     0, } -1651     
       MOV.I  <    15, {     1     
       SPL.B  $ -3145, <  1719     
       MOV.I  {    28, {     2     
       SPL.B  *    -2, <  -899     
       DJN.F  $   560, <   821     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $   -18, $  3452     
       DAT.F  $   -19, $  1383     
       DAT.F  $     0, $     0     
       SPL.B  #     0, $     6     
       MOV.I  $  -260, @     2     
       ADD.AB #    34, $     1     
       MOV.I  $  -262, }   754     
       DJN.F  $    -3, {  2926     
       DAT.F  $     0, $     0     
       DAT.F  }    17, >     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $   561, {     3     
       MOV.I  }     2, }    -1     
       MOV.I  $     3, >  -843     
       MOV.I  $     3, }    -3     
       JMZ.F  $    -4, *    -1     
       DAT.F  < -2666, <  2667     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.AB #     0, #     0     
       SNE.AB #    -1, $    -1     
       JMP.B  $   -93, > -3433     
       LDP.A  #   302, $    -3     
       ADD.A  #     1, @    -4     
       MOD.A  #     2, $    -5     
       STP.AB $    -6, #   302     
       JMZ.A  $   -54, $    -7     
       JMP.B  $   -97, } -1457     
       PIN         10
       END
