       ORG          0
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     0, <     3     
       SPL.B  $    -1, <    -5     
       MOV.I  $     8, <    -1     
       JMN.B  $    -2, #    64     
       DAT.F  $    -4, $     4     
       MOV.I  $    -8, $     8     
       JMP.B  $   -16, $    16     
       CMP.I  $   -32, $    32     
       MOV.I  $   -64, $    64     
       CMP.I  $  2516, $  2516     
       DAT.F  $     0, $     0     
       ADD.F  @     2, $     1     
       CMP.I  $   -84, $    84     
       JMP.B  $     2, $    -5     
       DJN.B  $    -3, @    -2     
       MOV.I  $    17, $   -17     
       SLT.B  $    -4, # -3030     
       JMP.B  $     4, <    -4     
       JMZ.B  $     8, @    -6     
       ADD.F  $    -7, $   -21     
       JMP.B  $     7, $   -13     
       MOV.I  $   -12, $    -9     
       SUB.F  <    -2, $   -10     
       DJN.B  $   -11, #     4     
       MOV.I  $   -14, <     1     
       JMP.B  $    -1, <   -28     
       SUB.F  $   -14, $   -28     
       MOV.I  $   -29, @   -29     
       MOV.AB #     9, #     0     
       MOV.I  $   -19, <   -31     
       MOV.I  $   -17, <   -32     
       DJN.B  $    -2, $    -3     
       JMP.B  $   -21, $    23     
       END
