       ORG          0
       ADD.F  $    12, $     1     
       CMP.I  $   -62, $    -8     
       SLT.AB #   100, $    -1     
       JMP.B  $    -3, $     0     
       MOV.I  $    18, $    17     
       SUB.F  $    -4, $    16     
       MOV.I  $    14, @    -5     
       MOV.I  $    14, <    -6     
       ADD.F  $     3, $    -7     
       JMP.B  $    -8, $     0     
       DAT.F  #     0, #     0     
       MOV.I  @   -54, <   -53     
       DAT.F  #  -108, #  -108     
       JMP.B  $    24, $     0     
       MOV.I  $    -1, $   -14     
       MOV.I  $   -16, <   -16     
       SPL.B  $    -1, <   -18     
       SPL.B  $    -2, <   -19     
       SPL.B  $    -3, <   -20     
       JMP.B  $    -4, <   -21     
       JMP.B  $    -1, $     0     
       JMP.B  $     0, $     0     
       JMP.B  $   -40, $     0     
       MOV.I  $     0, $     1     
       MOV.I  $    -1, $   200     
       SPL.B  $   199, $     0     
       MOV.AB #     7, $    -1     
       MOV.I  @    -2, <     5     
       DJN.B  $    -1, $    -3     
       SPL.B  @     3, $     0     
       ADD.AB #   653, $     2     
       JMZ.B  $    -5, $    -6     
       DAT.F  #     0, #   832     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       END
