       ORG         60
       MOV.AB #     1, $     1     
       MOV.I  $     3, @     2     
       MOV.I  $     5, <     9     
       SUB.F  $     7, $     1     
       MOV.I  $    68, <    74     
       JMZ.B  @    -4, <    -1     
       DJN.B  $    -6, #    17     
       SPL.B  $     0, <   -69     
       MOV.I  $     2, <   -13     
       DJN.B  $    -1, <  2652     
       DAT.F  <   -70, #   -71     
       DAT.F  <   -70, #  3500     
       MOV.I  $    -1, $   771     
       MOV.I  <     7, <    -1     
       MOV.I  <     6, <    -2     
       MOV.I  <     5, <    -3     
       MOV.I  <     4, <    -4     
       MOV.I  <     3, <    -5     
       MOV.I  <     2, <    -6     
       DJN.B  $    -5, #     2     
       JMP.B  $   756, $    -9     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       CMP.I  $  -717, $ -3716     
       JMP.B  $    27, < -1574     
       CMP.I  $ -2293, $  2708     
       JMP.B  $    24, <   568     
       CMP.I  $  3563, $   564     
       DJN.B  $    22, #    -4     
       CMP.I  $ -2588, $   411     
       DJN.B  $    19, #    -4     
       CMP.I  $ -1731, $  3270     
       JMP.B  $    17, < -3148     
       CMP.I  $  -159, $ -3158     
       JMP.B  $    15, <    16     
       CMP.I  $ -3877, $  1124     
       JMP.B  $    13, <    -8     
       CMP.I  $  -452, $  2547     
       JMP.B  $    10, <    11     
       CMP.I  $ -1468, $  1531     
       DJN.B  $     8, #    -8     
       CMP.I  $  2252, $ -2749     
       JMP.B  $     6, <   -12     
       CMP.I  $  1684, $ -3317     
       JMP.B  $     4, <     6     
       CMP.I  $ -2034, $   965     
       JMP.B  $     2, <   -18     
       JMZ.B  $   -72, $   106     
       ADD.F  @    -8, $     7     
       ADD.F  @   -19, @    -1     
       ADD.F  @   -22, @    -2     
       CMP.I  @     4, <  1234     
       CMP.I  @     0, $     0     
       ADD.AB #  2999, $     2     
       MOV.I  $     4, @     1     
       MOV.I  <  2345, < -3748     
       SUB.AB #     9, @    -2     
       DJN.B  $    -3, #     6     
       JMP.B  $   -83, <    43     
       END
