       ORG         58
       JMP.B  $   -56, <   -30     
       ADD.F  @    72, $     7     
       ADD.F  @    63, @    -1     
       ADD.F  @    60, @    -2     
       CMP.I  @     4, <  1234     
       CMP.I  @     0, $     0     
       ADD.AB #  -164, $     2     
       MOV.I  $    -7, @     1     
       MOV.I  <  2345, <  -588     
       ADD.AB #     9, @    -2     
       DJN.B  $    -3, #    10     
       SPL.B  $    70, $     0     
       MOV.I  $    18, <     9     
       MOV.I  $    16, <     8     
       MOV.I  $    14, <     7     
       MOV.I  $    12, <     6     
       MOV.I  $    10, <     5     
       MOV.I  $     8, <     4     
       MOV.I  $     6, <     3     
       MOV.I  $     4, <     2     
       MOV.I  $     2, <     1     
       JMP.B  @     0, $ -1540     
       ADD.AB # -3298, @     2     
       JMZ.B  $    -1, @     2     
       MOV.I  $     5, @     1     
       MOV.I  $     2, <  3866     
       JMN.B  $    -4, @    -4     
       SPL.B  $     0, <     0     
       MOV.I  $     2, <    -9     
       JMP.B  $    -1, $     0     
       DAT.F  <    -2, <   -92     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       SPL.B  $    -5, $     1     
       SPL.B  $    -6, $     0     
       SPL.B  $    -7, $     1     
       SPL.B  $    -8, $     0     
       SPL.B  $     0, $     1     
       SPL.B  $    -1, $     0     
       SPL.B  $    -2, $     1     
       SPL.B  $    -3, $     0     
       SPL.B  $    -4, $     1     
       SPL.B  $    -5, $     0     
       SPL.B  $    -6, $     1     
       SPL.B  $    -7, $     0     
       SPL.B  $    -8, $     1     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       SPL.B  $    -5, $     1     
       SPL.B  $    -6, $     0     
       SPL.B  $    -7, $     1     
       SPL.B  $    -8, $     0     
       CMP.I  $  -802, $  -638     
       JMP.B  $   -55, <  -957     
       CMP.I  $ -1761, $ -1597     
       JMP.B  $   -58, < -1276     
       CMP.I  $ -1444, $ -1280     
       DJN.B  $   -60, #    -4     
       CMP.I  $ -3198, $ -3362     
       DJN.B  $   -63, #    -4     
       CMP.I  $ -3043, $ -2879     
       JMP.B  $   -65, < -1914     
       CMP.I  $ -2088, $ -1924     
       JMP.B  $   -67, <   -66     
       CMP.I  $ -2728, $ -2564     
       JMP.B  $   -69, <    -8     
       CMP.I  $  2236, $  2072     
       DJN.B  $   -72, #    -6     
       CMP.I  $ -3525, $ -3689     
       JMP.B  $   -74, <   -73     
       CMP.I  $  2876, $  2712     
       JMP.B  $   -76, <   -12     
       CMP.I  $ -3848, $  3988     
       JMP.B  $   -78, <   -76     
       SPL.B  $   -68, $     0     
       MOV.I  $    18, <     9     
       MOV.I  $    16, <     8     
       MOV.I  $    14, <     7     
       MOV.I  $    12, <     6     
       MOV.I  $    10, <     5     
       MOV.I  $     8, <     4     
       MOV.I  $     6, <     3     
       MOV.I  $     4, <     2     
       MOV.I  $     2, <     1     
       JMP.B  @     0, $  2391     
       ADD.AB # -3298, @     2     
       JMZ.B  $    -1, @     2     
       MOV.I  $     5, @     1     
       MOV.I  $     2, <  3866     
       JMN.B  $    -4, @    -4     
       SPL.B  $     0, <     0     
       MOV.I  $     2, <    -9     
       JMP.B  $    -1, $     0     
       DAT.F  <    -2, <   -92     
       END
