       ORG         78
       SPL.B  $     1, #     1     
       SPL.B  $     2, #     1     
       SPL.B  $     3, #     1     
       SPL.B  $     4, #     1     
       SPL.B  $     5, #     1     
       SPL.B  $     6, #     1     
       SPL.B  $     7, #     1     
       SPL.B  $     8, #     1     
       SPL.B  $     9, #     1     
       SPL.B  $    10, #     1     
       SPL.B  $    11, #     1     
       SPL.B  $    12, #     1     
       SPL.B  $    13, #     1     
       SPL.B  $    14, #     1     
       SPL.B  $    15, #     1     
       SPL.B  $    16, #     1     
       SPL.B  $    17, #     1     
       SPL.B  $    18, #     1     
       SPL.B  $    19, #     1     
       SPL.B  $    20, #     1     
       SPL.B  $    21, #     1     
       SPL.B  $    22, #     1     
       SPL.B  $    23, #     1     
       SPL.B  $    24, #     1     
       SPL.B  $    25, #     1     
       SPL.B  $    26, #     1     
       SPL.B  $    27, #     1     
       SPL.B  $    28, #     1     
       SPL.B  $    29, #     1     
       SPL.B  $    30, #     1     
       SPL.B  $    31, #     1     
       SPL.B  $    32, #     1     
       SPL.B  $    33, #     1     
       SPL.B  $    34, #     1     
       SPL.B  $    35, #     1     
       SPL.B  $    36, #     1     
       SPL.B  $    37, #     1     
       SPL.B  $    38, #     1     
       SPL.B  $    39, #     1     
       SPL.B  $    40, #     1     
       SPL.B  $    41, #     1     
       SPL.B  $    42, #     1     
       SPL.B  $    43, #     1     
       SPL.B  $    44, #     1     
       SPL.B  $    45, #     1     
       SPL.B  $    46, #     1     
       SPL.B  $    47, #     1     
       SPL.B  $    48, #     1     
       SPL.B  $    49, #     1     
       SPL.B  $    50, #     1     
       SPL.B  $    51, #     1     
       SPL.B  $    52, #     1     
       SPL.B  $    53, #     1     
       SPL.B  $    54, #     1     
       SPL.B  $    55, #     1     
       SPL.B  $    56, #     1     
       SPL.B  $    57, #     1     
       SPL.B  $    58, #     1     
       SPL.B  $    59, #     1     
       SPL.B  $    60, #     1     
       SPL.B  $    61, #     1     
       SPL.B  $    62, #     1     
       SPL.B  $    63, #     1     
       SPL.B  $    64, #     1     
       SPL.B  $    65, #     1     
       SPL.B  $    66, #     1     
       SPL.B  $    67, #     1     
       SPL.B  $    68, #     1     
       SPL.B  $    69, #     1     
       SPL.B  $    70, #     1     
       MOV.I  <  2000, $     0     
       MOV.I  <    21, $  2235     
       SUB.F  $     1, $    -1     
       JMP.B  $    -2, < -2234     
       MOV.I  $     4, <    12     
       JMP.B  $    -1, <   -12     
       DAT.F  <  2667, #   -12     
       MOV.I  <  2663, <  2663     
       MOV.I  $    -5, $     2     
       MOV.I  $    -7, <    -1     
       MOV.I  $    -9, <    -2     
       MOV.I  $   -11, <    -3     
       MOV.I  $    -5, $ -2572     
       MOV.I  $    -8, $  2590     
       MOV.I  $   -10, <    -1     
       MOV.I  $    -9, $  2595     
       MOV.AB # -1744, $  2604     
       MOV.I  $   -10, $  2609     
       SPL.B  $  2594, <    -5     
       SPL.B  $     1, $     0     
       MOV.I  $    -1, $     0     
       SPL.B  $     1, $     0     
       JMP.B  @     1, <     1     
       DAT.F  #     0, #     6     
       JMP.B  $  -354, $     0     
       JMP.B  $  -356, $     0     
       JMP.B  $  -358, $     0     
       JMP.B  $  -357, $    -1     
       JMP.B  $  -360, $     0     
       JMP.B  $  -362, $     0     
       END
