       ORG          0
       LDP.A  #     1, $     1     
       SUB.AB #     0, #     1     
       STP.B  $    -1, #     1     
       JMN.B  $    65, $    -2     
       SPL.A  $    10, >  1000     
       SPL.A  $    16, >  2000     
       SPL.A  $    22, >  3000     
       SPL.A  $    28, >  4000     
       SPL.A  $    34, > -3000     
       SPL.A  $    40, > -2000     
       SPL.A  $    46, > -1000     
       JMP.A  $    52, >  -500     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, > -2667     
       DAT.F  $     1, $   883     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, > -1143     
       DAT.F  $     1, $  1257     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, >  -889     
       DAT.F  $     1, $  -573     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, >  2909     
       DAT.F  $     1, $  3139     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, > -3077     
       DAT.F  $     1, $ -2047     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, > -2353     
       DAT.F  $     1, $  2155     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, >   421     
       DAT.F  $     1, $  3803     
       MOV.A  #     1, $     6     
       MOV.AB #     7, $     2     
       MOV.I  {     4, <     4     
       DJN.B  $    -1, #     7     
       SPL.A  $    -4, }     2     
       JMP.A  @     1, >  -381     
       DAT.F  $     1, $  -921     
       SPL.B  $   129, $     0     
       SPL.B  $   128, $     0     
       SPL.B  $   127, $     0     
       SPL.B  $   126, $     0     
       MOV.I  $     7, $   178     
       SPL.B  $     1, $     0     
       SPL.B  $     2, $     0     
       JMP.B  *     2, }     0     
       JMP.B  @     1, }     0     
       DAT.F  $   173, $  2840     
       DAT.F  $ -2494, $   173     
       MOV.I  #     0, $  2667     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  <    -1, $  2235     
       ADD.X  #  2234, $    -1     
       JMP.B  $    -2, {    -2     
       END
