       ORG         88
       MOV.I  $     5, <     6     
       JMP.B  $    -1, <     5     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $   -11     
       DAT.F  $     0, $   -31     
       MOV.I  $    -7, $  2535     
       MOV.I  $    -7, $  2535     
       MOV.I  $    -4, $  2538     
       MOV.I  $    -4, $  2538     
       SPL.B  $  2531, $     0     
       SPL.B  $    60, $     0     
       SPL.B  $    59, $     0     
       SPL.B  $    58, $     0     
       SPL.B  $    57, $     0     
       SPL.B  $    56, $     0     
       JMP.B  $    60, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, $    10     
       MOV.I  $    27, >     9     
       JMP.B  $    -2, $     8     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $    50     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  #     0, #     0     
       DAT.F  $     0, $     0     
       SPL.B  #   -15, $    15     
       DAT.F  $     0, $     0     
       ADD.F  $    -2, $    11     
       MOV.I  $    10, @    10     
       MOV.I  $    -6, *     9     
       JMP.B  $    -3, @    -2     
       DAT.F  $     0, $     0     
       MOV.I  $     3, >   -15     
       JMP.B  $    -1, $   -16     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $    50     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  $   -82, $    51     
       DAT.F  $     0, $     4     
       DAT.F  $     0, $     1     
       DAT.F  $     1, $    -1     
       DAT.F  $     1, $     0     
       LDP.A  #     0, $    -3     
       LDP.A  #   250, $     4     
       MOD.A  #    18, $     3     
       ADD.BA *    -6, $     2     
       STP.A  *     1, $    -3     
       JMP.B  @     1, $   -86     
       SPL.B  #     1, $   -87     
       SPL.B  #     2, $   -88     
       SPL.B  #     3, $   -89     
       SPL.B  #     4, $   -90     
       SPL.B  #    10, $    50     
       SPL.B  #     7, $    49     
       SPL.B  #     7, $    48     
       SPL.B  #     8, $    47     
       SPL.B  #     9, $    46     
       SPL.B  #    10, $    45     
       SPL.B  #    16, $    83     
       SPL.B  #    13, $    82     
       SPL.B  #    13, $    81     
       SPL.B  #    14, $    80     
       SPL.B  #    15, $    79     
       SPL.B  #    16, $    78     
       SPL.B  #     4, $  -103     
       MOV.AB #     6, #     0     
       MOV.I  <    -1, <     3     
       JMN.B  $    -1, @    -2     
       SPL.B  @    -3, <  2151     
       JMZ.B  @     0, $  3039     
       DAT.F  {     1, <     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       ADD.F  $     2, $     1     
       MOV.I  >   -40, $  2920     
       JMP.B  $    -2, <  2946     
       MOV.I  $    -1, {     5     
       MOV.I  $    -3, {     4     
       MOV.I  $    -5, {     3     
       SPL.B  $   -40, {     0     
       SPL.B  $    29, {     0     
       SPL.B  $  -798, $     0     
       SPL.B  *    -1, $     0     
       SPL.B  *    -2, $     0     
       JMP.B  *    -3, {    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.AB #     6, #     0     
       MOV.I  <    -1, <     3     
       JMN.B  $    -1, @    -2     
       SPL.B  @    -3, <  2151     
       JMZ.B  @     0, $  3359     
       DAT.F  {     1, <     1     
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       JMP.B  *     1, }     0     
       DAT.F  $     8, $     0     
       DAT.F  $  2674, $     0     
       DAT.F  $ -2660, $     0     
       DAT.F  $     6, $     0     
       DAT.F  $  2672, $     0     
       DAT.F  $ -2662, $     0     
       DAT.F  $     4, $     0     
       DAT.F  $  2670, $     0     
       MOV.I  #     0, $  2667     
       END
