       ORG         59
       DAT.F  #     0, #     0     
       MOV.I  $    23, $    -1     
       MOV.I  $    22, $    -2     
       MOV.I  $    21, $    -3     
       MOV.I  $    20, $    -4     
       MOV.I  $    19, $    -5     
       MOV.I  $    18, $    -6     
       MOV.I  $    17, $    -7     
       MOV.I  $    16, $    -8     
       MOV.I  $    15, $    -9     
       MOV.I  $    14, $   -10     
       MOV.I  $    13, $   -11     
       MOV.I  $    12, $   -12     
       MOV.I  $    11, $   -13     
       MOV.I  $    10, $   -14     
       MOV.I  $     9, $   -15     
       MOV.I  $     8, $   -16     
       MOV.I  $     7, $   -17     
       MOV.I  $     6, $   -18     
       MOV.I  $     5, $   -19     
       MOV.I  $     4, $   -20     
       MOV.I  $     3, $   -21     
       MOV.I  $     2, $   -22     
       MOV.I  $     1, $   -23     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #  -110     
       SPL.B  $    40, $     0     
       DAT.F  #     0, #   700     
       MOV.I  $    -4, @    -3     
       SUB.AB #    10, $    -4     
       MOV.I  $    -6, @    -4     
       ADD.AB #    10, $    -5     
       DJN.B  $     4, $    -5     
       MOV.AB #    40, $    -7     
       MOV.AB #  -110, $    -9     
       MOV.AB #   700, $    -8     
       JMZ.B  $    -8, $  -136     
       SPL.B  $   -36, $     0     
       SPL.B  $   -37, $     0     
       SPL.B  $   -38, $     0     
       SPL.B  $   -39, $     0     
       SPL.B  $   -40, $     0     
       SPL.B  $   -41, $     0     
       SPL.B  $   -42, $     0     
       SPL.B  $   -43, $     0     
       SPL.B  $   -44, $     0     
       SPL.B  $   -45, $     0     
       SPL.B  $   -46, $     0     
       SPL.B  $   -47, $     0     
       SPL.B  $   -48, $     0     
       SPL.B  $   -49, $     0     
       SPL.B  $   -50, $     0     
       SPL.B  $   -51, $     0     
       SPL.B  $   -52, $     0     
       SPL.B  $   -53, $     0     
       SPL.B  $   -54, $     0     
       SPL.B  $     7, $     0     
       MOV.I  $   -33, $  -157     
       JMP.B  $   -30, $     0     
       SPL.B  $     4, $     0     
       MOV.I  $   -36, $  -160     
       JMP.B  $   -33, $     0     
       DAT.F  #     0, #   100     
       MOV.I  $     0, $     1     
       END
