       ORG          0
       MOV.I  $    46, @ -2304     
       MOV.I  $    45, @ -2817     
       MOV.I  $    44, @ -3330     
       MOV.I  $    43, @ -3843     
       MOV.I  $    42, @  3644     
       MOV.I  $    41, @  3131     
       MOV.I  $    40, @  2618     
       MOV.AB #    -2, $    40     
       JMN.B  <     0, @   112     
       JMN.B  <     0, @   136     
       JMN.B  <     0, @   160     
       JMN.B  <     0, @   184     
       DJN.B  $    -4, $     2     
       JMP.B  $    36, $     0     
       DAT.F  #     0, #    25     
       MOV.I  @    -7, $    33     
       ADD.F  $    -8, $    32     
       JMP.B  $     9, $     0     
       MOV.I  @    -9, $    30     
       ADD.F  $   -10, $    29     
       JMP.B  $     6, $     0     
       MOV.I  @   -11, $    27     
       ADD.F  $   -12, $    26     
       JMP.B  $     3, $     0     
       MOV.I  @   -13, $    24     
       ADD.F  $   -14, $    23     
       ADD.AB #    50, $    22     
       MOV.I  $    20, <    21     
       MOV.I  $    18, <    20     
       MOV.I  $    16, <    19     
       MOV.I  $    14, <    18     
       MOV.I  $    12, <    17     
       MOV.I  $    10, <    16     
       MOV.I  $     8, <    15     
       MOV.I  $     6, <    14     
       MOV.I  $     4, <    13     
       MOV.I  $     2, <    12     
       JMP.B  @    11, $     0     
       MOV.I  @     8, <     4     
       MOV.I  @     4, <     3     
       DJN.B  $    -2, $     2     
       DAT.F  #     0, #    -9     
       DAT.F  #     0, #    -9     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #    -2     
       SPL.B  $     0, $     0     
       DAT.F  #     0, #     1     
       JMP.B  $    -1, $     0     
       DAT.F  #     0, # -3904     
       MOV.AB #   -27, $    35     
       MOV.AB #    20, $    33     
       MOV.AB #   741, $    31     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       MOV.I  $    21, $ -3904     
       JMP.B  $ -3914, $     0     
       JMP.B  $     1, $     0     
       DJN.B  $     3, $     2     
       MOV.I  $     1, $     2     
       DAT.F  #     0, #    64     
       SPL.B  $    -3, $     0     
       MOV.I  $    13, <    13     
       JMP.B  $    -2, $     0     
       JMP.B  @     0, $     0     
       JMP.B  @     0, $     0     
       MOV.I  $    -1, @    -2     
       MOV.I  $    -3, <    -2     
       ADD.AB #    11, $    -4     
       SUB.AB #    10, $    -4     
       DJN.B  $    -4, $    -7     
       MOV.I  $     2, <     3     
       DJN.B  $    -1, $     2     
       DAT.F  #     0, #    -5     
       DAT.F  #     0, #   -17     
       DAT.F  #     0, #   768     
       JMN.B  $   -80, $  2460     
       JMN.B  $   -81, $  2496     
       JMN.B  $   -82, $  2532     
       JMN.B  $   -83, $  2568     
       JMN.B  $   -84, $  2604     
       JMN.B  $   -85, $  2640     
       JMN.B  $   -86, $  2676     
       JMN.B  $   -87, $  2712     
       JMN.B  $   -88, $  2748     
       JMN.B  $   -89, $  2784     
       JMN.B  $   -90, $  2820     
       JMN.B  $   -91, $  2856     
       JMN.B  $   -92, $  2892     
       JMN.B  $   -93, $  2928     
       JMN.B  $   -94, $  2964     
       JMN.B  $   -95, $  3000     
       JMN.B  $   -96, $  3036     
       JMN.B  $   -97, $  3072     
       JMN.B  $   -98, $  3108     
       JMN.B  $   -99, $  3144     
       JMN.B  $  -100, $  3180     
       JMN.B  $  -101, $  3216     
       JMN.B  $  -102, $  3252     
       JMN.B  $  -103, $  3288     
       JMN.B  $  -104, $  3324     
       JMN.B  $  -102, $  3360     
       JMN.B  $  -103, $  3396     
       JMN.B  $  -104, $  3432     
       JMN.B  $  -105, $  3468     
       JMN.B  $  -106, $  3504     
       JMN.B  $  -107, $  3540     
       JMN.B  $  -108, $  3576     
       JMN.B  $  -109, $  3612     
       JMN.B  $  -110, $  3648     
       JMN.B  $  -111, $  3684     
       JMN.B  $  -112, $  3720     
       JMN.B  $  -113, $  3756     
       JMN.B  $  -114, $  3792     
       JMN.B  $  -115, $  3828     
       JMN.B  $  -116, $  3864     
       JMN.B  $  -117, $  3900     
       JMN.B  $  -118, $  3936     
       JMN.B  $  -119, $  3972     
       JMN.B  $  -120, $ -3992     
       JMN.B  $  -121, $ -3956     
       JMN.B  $  -122, $ -3920     
       JMN.B  $  -123, $ -3884     
       JMN.B  $  -124, $ -3848     
       JMN.B  $  -125, $ -3812     
       JMN.B  $  -126, $ -3776     
       JMN.B  $  -124, $ -3740     
       JMN.B  $  -125, $ -3704     
       JMN.B  $  -126, $ -3668     
       JMN.B  $  -127, $ -3632     
       JMN.B  $  -128, $ -3596     
       JMN.B  $  -129, $ -3560     
       JMN.B  $  -130, $ -3524     
       JMN.B  $  -131, $ -3488     
       JMN.B  $  -132, $ -3452     
       JMN.B  $  -133, $ -3416     
       JMN.B  $  -134, $ -3380     
       JMN.B  $  -135, $ -3344     
       JMN.B  $  -136, $ -3308     
       JMN.B  $  -137, $ -3272     
       JMN.B  $  -138, $ -3236     
       JMN.B  $  -139, $ -3200     
       JMN.B  $  -140, $ -3164     
       JMN.B  $  -141, $ -3128     
       JMN.B  $  -142, $ -3092     
       JMN.B  $  -143, $ -3056     
       JMN.B  $  -144, $ -3020     
       JMN.B  $  -145, $ -2984     
       JMN.B  $  -146, $ -2948     
       JMN.B  $  -147, $ -2912     
       JMN.B  $  -148, $ -2876     
       JMN.B  $  -146, $ -2840     
       JMN.B  $  -147, $ -2804     
       JMN.B  $  -148, $ -2768     
       JMN.B  $  -149, $ -2732     
       JMN.B  $  -150, $ -2696     
       JMN.B  $  -151, $ -2660     
       JMN.B  $  -152, $ -2624     
       JMN.B  $  -153, $ -2588     
       JMN.B  $  -154, $ -2552     
       JMN.B  $  -155, $ -2516     
       JMN.B  $  -156, $ -2480     
       JMN.B  $  -157, $ -2444     
       JMN.B  $  -158, $ -2408     
       JMN.B  $  -159, $ -2372     
       JMN.B  $  -160, $ -2336     
       JMN.B  $  -161, $ -2300     
       JMN.B  $  -162, $ -2264     
       JMN.B  $  -163, $ -2228     
       JMN.B  $  -164, $ -2192     
       JMN.B  $  -165, $ -2156     
       JMN.B  $  -166, $ -2120     
       JMN.B  $  -167, $ -2084     
       JMN.B  $  -168, $ -2048     
       JMN.B  $  -169, $ -2012     
       JMN.B  $  -170, $ -1976     
       DAT.F  #     0, # -1940     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     2     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       END
