       ORG         53
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, $     0     
       SPL.B  $     5, $     0     
       MOV.I  $    -1, $     0     
       JMP.B  $    -4, $     0     
       SPL.B  $     0, #  1156     
       ADD.F  $    -1, $     1     
       MOV.I  $    -2, $     1     
       JMP.B  $    -2, $     0     
       SPL.B  $     0, $     0     
       MOV.I  $     0, $     1     
       MOV.I  $    -6, $  1118     
       MOV.I  $    -6, $  1118     
       MOV.I  $    -6, $  1118     
       MOV.I  $    -6, $  1118     
       MOV.I  $    -6, $  1118     
       MOV.I  $    -6, $  1118     
       JMP.B  $  1112, $     0     
       SPL.B  $    -7, $     0     
       JMP.B  $     2, $     0     
       JMP.B  $ -2727, $     0     
       SPL.B  $    -1, $     0     
       SPL.B  $  2732, $     0     
       MOV.I  $     0, $  2731     
       END
