       ORG         11
       JMP.B  $     0, $     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $   -11, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $     2, $     0     
       JMP.B  @     0, $    22     
       ADD.AB #     1, $    -1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     4, @     1     
       MOV.I  $     3, @   -50     
       ADD.AB #    -2, $    -1     
       JMP.B  $    -3, $     0     
       DAT.F  #     1, #    -1     
       END
