       ORG         21
       SPL.B  $     1, <  1538     
       SPL.B  $     1, <  -727     
       SPL.B  $     1, < -1767     
       MOV.I  <     1, {     1     
       JMP.B  $ -4087, $     9     
       SPL.B  @     0, }   767     
       MOV.I  }    -1, >    -1     
       MOV.I  $     5, > -1064     
       MOV.I  $     3, } -3680     
       MOV.I  {    -4, <     1     
       JMP.B  @     0, >   657     
       DAT.F  >  2731, > -2730     
       DAT.F  >     1, }     1     
       DAT.F  $     0, $   -13     
       DAT.F  $     0, $    17     
       DAT.F  $     0, $   -15     
       DAT.F  $     0, $    15     
       DAT.F  $     0, $   -17     
       DAT.F  $     0, $    13     
       DAT.F  $     0, $    37     
       DAT.F  $     0, $    11     
       LDP.AB #     0, #     0     
       LDP.AB #    94, #     0     
       SNE.AB #     0, $    -2     
       ADD.AB #     1, $    -2     
       SNE.AB #     2, $    -4     
       MOV.AB #     6, $    -4     
       STP.BA $    -5, $    -5     
       MOD.AB #     8, $    -6     
       ADD.BA $    -7, $     1     
       JMP.B  @   -17, {    -8     
       MOV.I  $    24, $   -19     
       MOV.I  *    12, @    12     
       MOV.I  {    11, <    11     
       MOV.I  {    10, <    10     
       MOV.I  {     9, <     9     
       MOV.I  {     8, <     8     
       MOV.I  {     7, <     7     
       MOV.I  {     6, <     6     
       MOV.I  {     5, <     5     
       MOV.I  {     4, <     4     
       MOV.I  {     3, <     3     
       MOV.I  {     2, <     2     
       JMP.B  >     1, {  -943     
       DAT.F  $    11, $ -4085     
       MOV.I  $    10, *     2     
       MOV.I  $     8, @     1     
       MOV.I  $   121, @   239     
       ADD.F  $     2, $    -1     
       DJN.F  $    -4, {  -904     
       SPL.B  #   355, #   355     
       MOV.I  $   -12, }    -5     
       MOV.I  $   -13, }    -6     
       DJN.F  $    -1, {    -9     
       DJN.F  $     3, {   124     
       DAT.F  {     0, <     0     
       MOV.I  $    -1, $   -44     
       MOV.I  @     6, *     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       ADD.A  #     1, $     1     
       JMP.B  $ -4091, $     5     
       DAT.F  #    -5, $     8     
       SPL.B  # -2142, $   150     
       MOV.I  @     2, >    -5     
       MOV.I  @     1, >    -6     
       DJN.B  $    -2, {    -3     
       PIN        768
       END
