       ORG         62
       DAT.F  >   -86, >  1978     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, <  2707     
       SPL.B  $     1, <  2950     
       SPL.B  $     1, <  3193     
       MOV.I  {    22, {     1     
       SPL.B  $ -2596, { -2445     
       MOV.I  {    28, {     1     
       JMP.B  $   499, { -3608     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $   -19, $ -1840     
       DAT.F  $   -20, $ -1597     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     8, <  1601     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <  3137     
       MOV.I  }    -1, >    -1     
       MOV.I  $     3, <   641     
       MOV.I  {    -3, {     1     
       DJN.F  $   705, > -3964     
       DAT.F  < -2858, <  2667     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     8, $  1344     
       MOV.I  $    12, $  1354     
       SPL.B  $     2, >  2689     
       SPL.B  $     2, > -1630     
       SPL.B  $     1, $  1346     
       MOV.I  <     2, <    -1     
       DJN.B  @    -6, #     5     
       JMP.B  $   -52, $     6     
       SPL.B  #     0, $     0     
       MOV.I  $     9, @     2     
       ADD.AB #  3900, $     1     
       MOV.I  $     7, }  1445     
       DJN.F  $    -3, < -3915     
       DAT.F  $ -2146, >     1     
       SNE.I  $   -73, $  2877     
       SEQ.I  <   -63, $   768     
       JMP.B  $    25, }    25     
       SNE.I  $   464, $  3414     
       SEQ.I  <   -47, $  1305     
       JMP.B  $    22, {    22     
       SNE.I  $ -3879, $  -929     
       SEQ.I  <   -51, $ -3038     
       DJN.A  $    19, {    19     
       SNE.I  $ -2958, $   235     
       SEQ.I  <   -67, $ -1875     
       JMP.B  $    16, }    18     
       SNE.I  $ -3449, $  -742     
       SEQ.I  <   -72, $ -2852     
       JMP.B  $    13, {    15     
       SNE.I  $   888, $  3838     
       SEQ.I  <   -74, $  1728     
       JMP.B  $    10, $     0     
       SEQ.I  >    13, $ -3122     
       JMP.B  $     9, <    12     
       SEQ.I  $  -224, $  2725     
       JMP.B  $     6, }     6     
       SEQ.I  $ -3261, $  -312     
       JMP.B  $     4, {     4     
       SEQ.I  $   346, $  3295     
       DJN.A  $     2, {     2     
       JMZ.F  $     8, $ -3525     
       MUL.B  *     2, $     4     
       SNE.I  {   -71, @     3     
       ADD.B  $   -87, $     2     
       MOV.I  $   -92, @     1     
       MOV.I  $   -93, }  2108     
       SUB.AB #    -7, $    -1     
       DJN.B  $    -3, #    19     
       LDP.AB #     0, $     2     
       LDP.A  #     1, $     6     
       SNE.AB #     1, #     0     
       JMP.B  $     8, $     0     
       ADD.A  #     1, $     3     
       MOD.A  #     4, $     2     
       STP.A  $     1, #     1     
       JMP.B  @     0, $   -55     
       NOP.F  $     0, $   -56     
       NOP.F  $     0, $   182     
       NOP.F  $     0, $   181     
       MOV.AB $    -4, #     0     
       MOD.AB #     2, $    -1     
       SUB.BA $    -2, $    -6     
       JMP.B  $    -8, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $   100, $  4096     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $    12, <    -7     
       MOV.I  >    -8, >    -8     
       JMN.F  $    -2, >    -9     
       SUB.X  #   -14, $   -10     
       SNE.X  *   -11, >   -11     
       SUB.X  *     3, @    -2     
       JMN.F  $     3, <   -13     
       JMZ.F  $    -4, *   -14     
       MOV.X  @    -5, @    -5     
       SLT.B  @    -6, #    26     
       DJN.B  $   -10, @    -7     
       DJN.B  *    -3, #    10     
       SPL.B  #     0, }     0     
       MOV.I  $     2, >    -4     
       DJN.F  $    -1, {    -5     
       DAT.F  >     1, $     8     
       END
