       ORG        205
       MOD.F  }     0, >    -3     
       DAT.F  $     0, $     0     
       MOD.F  }     0, >     1     
       DAT.F  $     0, $     0     
       SPL.B  $     1, <   969     
       SPL.B  $     1, <  1212     
       SPL.B  $ -2232, <  1455     
       MOV.I  }     9, }    -1     
       SPL.B  $  1854, $     0     
       MOV.I  }     6, }    -1     
       SPL.B  $     1, $     0     
       MOV.I  <     1, {     1     
       SPL.B  $  2133, $    49     
       MOV.I  <     1, {     1     
       JMP.B  $  1284, $    39     
       DAT.F  $   116, $  3642     
       DAT.F  $   115, $  3885     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     0, <   817     
       MOV.I  }    -1, >    -1     
       SPL.B  $ -2505, $     0     
       MOV.I  >    -1, }    -1     
       SPL.B  # -3607, > -1605     
       MOV.I  {   527, {  1260     
       ADD.F  $    -2, $    -1     
       DJN.F  @     0, {    -2     
       SPL.B  @     0, < -2041     
       MOV.I  }    -1, >    -1     
       SPL.B  $  2432, #     0     
       MOV.I  >    -1, }    -1     
       SPL.B  @     0, <  1651     
       MOV.I  }    -1, >    -1     
       MOV.I  #     1, <     1     
       DJN.B  $    -2, <  3566     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, <  1818     
       MOV.I  $   183, $ -1523     
       ADD.AB {     0, }     0     
       DJN.F  $    -2, <  1815     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SNE.I  $  1899, $  3111     
       SEQ.I  <  -206, $  1002     
       JMP.B  $    25, }    25     
       SNE.I  $ -2392, $ -1180     
       SEQ.I  <  -193, $ -3289     
       JMP.B  $    22, {    22     
       SNE.I  $  1457, $  2669     
       SEQ.I  <  -197, $   560     
       DJN.A  $    19, {    19     
       SNE.I  $  3354, $ -3383     
       SEQ.I  <  -209, $  2699     
       JMP.B  $    16, }    18     
       SNE.I  $  2863, $  3832     
       SEQ.I  <  -214, $  1722     
       JMP.B  $    13, {    15     
       SNE.I  $  -992, $   220     
       SEQ.I  <  -216, $ -1890     
       JMP.B  $    10, $     0     
       SEQ.I  >    13, $  3332     
       JMP.B  $     9, <    12     
       SEQ.I  $  -233, $   978     
       JMP.B  $     6, }     6     
       SEQ.I  $  -635, $   576     
       JMP.B  $     4, {     4     
       SEQ.I  $  2972, $ -4009     
       DJN.A  $     2, {     2     
       JMZ.F  $  -227, $  -689     
       MUL.B  *     2, $     4     
       SNE.I  {  -217, @     3     
       ADD.B  $  -229, $     2     
       MOV.I  $  -235, @     1     
       MOV.I  $  -234, }  2108     
       SUB.AB #    -8, $    -1     
       MOV.I  $  -238, @    -2     
       MOV.I  $  -237, }  2108     
       SUB.AB #    -8, $    -4     
       MOV.I  $  -241, @    -5     
       MOV.I  $  -240, }  2108     
       SUB.AB #    -8, $    -7     
       MOV.I  $  -244, @    -8     
       MOV.I  $  -243, }  2108     
       SUB.AB #    -8, $   -10     
       MOV.I  $  -247, @   -11     
       MOV.I  $  -246, }  2108     
       SUB.AB #    -8, $   -13     
       MOV.I  $  -250, @   -14     
       MOV.I  $  -249, }  2108     
       SUB.AB #    -8, $   -16     
       JMP.B  $  -249, $     0     
       END
