       ORG        135
       MOV.I  <     2, {     2     
       DJN.B  $    -1, #     9     
       JMP.B  $   537, $    10     
       SNE.I  $   442, $  2992     
       ADD.F  $     7, $    -1     
       MOV.I  $     3, }    -2     
       MOV.I  $     2, >    -3     
       DJN.B  @    -2, #   323     
       SPL.B  #     1, $     1     
       MOV.I  $     2, >    -6     
       DJN.F  $    -1, >    -7     
       DAT.F  $    11, $    11     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     0, <  2216     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, { -3552     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, {  1573     
       MOV.I  }    -1, >    -1     
       MOV.I  #     1, {     1     
       MOV.I  $    -7, <    -7     
       MOV.I  {    -4, <     1     
       JMZ.A  @     0, $   338     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, <  2565     
       MOV.I  <     0, $     0     
       MOV.I  <     0, $     0     
       MOV.I  <     4, {     4     
       SPL.B  $     1, <  2762     
       MOV.I  <     1, {     1     
       SPL.B  $  2895, $   -26     
       JMP.B  $  3260, $    36     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, #     0     
       MOV.I  $     3, @     2     
       ADD.AB #   629, $     1     
       DJN.F  $    -2, {  2701     
       DAT.F  >  1518, >     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.AB #     0, #     0     
       LDP.A  #     1, $    10     
       JMN.B  $     7, $    -2     
       LDP.AB #     2, #     0     
       NOP.F  >    -1, }  -392     
       MOD.AB #     3, $    -2     
       JMN.B  $     3, $    -3     
       NOP.F  }     4, } -1168     
       STP.AB $     3, #     1     
       STP.B  $    -6, #     2     
       MOD.A  #     2, $     1     
       JMP.A  @     0, $  -146     
       DAT.F  $     0, $   -75     
       END
