       ORG        275
       MOV.I  $    12, >    -1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     7, >  3314     
       MOV.I  $    12, >    -1     
       SEQ.I  $   144, $   149     
       MOV.AB $    -1, @    -2     
       SUB.F  $     2, $    -2     
       JMN.B  $    -4, @    -4     
       SPL.I  #   -72, >   -72     
       MOV.I  $     2, >    -6     
       DJN.F  $    -1, >    -7     
       DAT.F  <  2731, $    10     
       DAT.F  $     0, $     0     
       SPL.I  #   -72, >   -72     
       DAT.F  $     0, $     0     
       SPL.I  #     1, #     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  {    -3, <     6     
       DAT.F  $     0, $     0     
       MOV.I  $    -9, <     9     
       MOV.I  {    -1, <     8     
       MOV.I  {    -2, <     7     
       MOV.I  {    -3, <     6     
       MOV.I  {    -4, <     5     
       MOV.I  {    -5, <     4     
       MOV.I  {    -6, <     3     
       MOV.I  {    -7, <     2     
       MOV.I  {    -8, <     1     
       MOV.I  $   -14, *  1977     
       SPL.B  @    -1, { -1001     
       JMP.B  $     4, } -2750     
       DAT.F  <    -3, <    -3     
       MOV.I  {    -8, <     1     
       SPL.A  #     1, *     1     
       MOV.I  {   -15, <    -6     
       MOV.I  $   -26, $   -21     
       MOV.I  $   241, $   246     
       MOV.I  $    -3, $    -8     
       MOV.I  $     4, $    -1     
       MOV.I  $   -29, $   -34     
       MOV.I  $   229, $   234     
       MOV.I  $   -15, $   -20     
       DAT.F  >   498, >  1701     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.A  #     1, *     1     
       SPL.B  #     1, $     1     
       SPL.AB #     1, @     1     
       SPL.BA #     1, }     1     
       SPL.I  #     1, #     1     
       SPL.I  #     1, #     1     
       STP.AB #    30, #     3     
       NOP.F  $     0, $     0     
       STP.AB #    39, #     3     
       LDP.AB #     0, #     0     
       SNE.AB #    -1, $    -1     
       JMP.B  $    13, $     0     
       LDP.AB #     3, #     0     
       SEQ.AB #    30, $    -1     
       JMP.B  $  -258, } -3814     
       STP.AB #    39, #     3     
       LDP.AB #     1, #     0     
       SEQ.AB #    10, $    -1     
       JMP.B  $  -262, >  4000     
       SEQ.AB #     0, $   -10     
       JMP.B  $   -14, >  3500     
       STP.AB #    10, #     1     
       NOP.F  $     0, $     0     
       DAT.F  #     0, $     0     
       STP.AB #    30, #     3     
       STP.AB #    10, #     1     
       NOP.F  $     0, $     0     
       NOP.F  $     0, $     0     
       LDP.AB #     2, #     0     
       SNE.AB #    20, $    -1     
       DAT.F  $     0, $     0     
       JMZ.F  $     0, {     1     
       SNE.I  #  -310, {     0     
       JMP.B  $     0, {    -1     
       PIN          3
       END
