       ORG         88
       SEQ.I  $    -1, @    15     
       ADD.AB #  2008, $    -1     
       MOV.I  {    13, <    13     
       MOV.I  {    12, <    12     
       MOV.I  {    11, <    11     
       MOV.I  {    10, <    10     
       MOV.I  {     9, <     9     
       MOV.I  {     8, <     8     
       MOV.I  {     7, <     7     
       MOV.I  {     6, <     6     
       MOV.I  {     5, <     5     
       MOV.I  {     4, <     4     
       MOV.I  {     3, <     3     
       SPL.B  @     2, #     0     
       MOV.I  $     2, $     1     
       DAT.F  #    85, #  2650     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       JMZ.F  $   -88, @     1     
       MOV.I  $     3, $  2011     
       MOV.I  $     4, <    -1     
       ADD.AB #  2006, $    -2     
       DJN.B  @    -1, #   300     
       JMP.B  $     3, $     3     
       SPL.B  #    -9, #     0     
       DAT.F  $  -100, $     9     
       SPL.B  #  -500, $    11     
       MOV.I  @     2, >    -5     
       MOV.I  @     1, >    -6     
       DJN.F  $    -2, {    -3     
       END
