       ORG         10
       MUL.B  *     2, $     4     
       SNE.I  <    27, @     3     
       ADD.B  $     6, $     2     
       MOV.I  $    26, @     1     
       MOV.I  $    25, *  -148     
       ADD.AB #    -7, $    -1     
       DJN.B  $    -3, #    18     
       JMP.B  $    73, $  2954     
       DAT.F  $  4000, $ -1395     
       DAT.F  $  4000, $  2256     
       SNE.I  $  2106, $ -3638     
       SEQ.I  <    -2, $ -3492     
       JMP.B  $   -12, }   -10     
       SNE.I  $  -509, $ -1904     
       SEQ.I  <    14, $ -1757     
       JMP.B  $   -15, {   -15     
       SNE.I  $  3836, $  2441     
       SEQ.I  <    10, $  2588     
       DJN.A  $   -18, {   -18     
       SNE.I  $  3137, $  1742     
       SEQ.I  <     9, $  1889     
       JMP.B  $   -21, }   -21     
       SNE.I  $  2790, $ -2256     
       SEQ.I  <   -16, $ -2110     
       JMP.B  $   -24, {   -22     
       SNE.I  $ -1561, $ -2956     
       SEQ.I  <   -18, $ -2810     
       JMP.B  $   -27, $  3974     
       JMP.B  $    52, $  -375     
       DAT.F  $    87, $  3276     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $    14, $ -1519     
       SPL.B  $     2, <   250     
       SPL.B  $     1, <   350     
       SPL.B  $     1, <   450     
       MOV.I  <     4, {     3     
       MOV.I  <    10, {     1     
       SPL.B  $ -1453, <   550     
       DJN.F  $ -3805, <   650     
       SPL.B  $ -3640, $     6     
       MOV.I  >    -1, }    -1     
       SPL.B  $  2668, $     0     
       MOV.I  >    -1, }    -1     
       SPL.B  $ -2666, <   345     
       MOV.I  #     1, $  2667     
       DAT.F  >    -1, >     1     
       SPL.B  #     0, $     6     
       SPL.B  #     0, $     0     
       MOV.I  $   -68, $    69     
       SUB.AB {     0, }     0     
       DJN.F  $    -2, <  1455     
       END
