       ORG         80
       MOV.B  $     3, #     5     
       MOV.I  *     1, >    -1     
       ADD.F  $     4, $     1     
       SEQ.I  }  1682, $  1674     
       DJN.F  $    -4, @    -4     
       JMP.B  $    -3, $     0     
       SPL.B  #  1681, <  1681     
       MOV.I  $     2, >    -4     
       DJN.F  $    -1, >    -5     
       DAT.F  $     1, $     8     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MUL.B  *     2, $     4     
       SNE.I  <    27, @     3     
       ADD.B  $     6, $     2     
       MOV.I  $    26, @     1     
       MOV.I  $    25, *  1742     
       ADD.AB #    -7, $    -1     
       DJN.B  $    -3, #    18     
       JMP.B  $   -74, $ -2416     
       DAT.F  $  4000, $  -555     
       DAT.F  $  4000, $  1306     
       SNE.I  $  3046, $ -3648     
       SEQ.I  <    -2, $  2608     
       JMP.B  $   -12, }   -10     
       SNE.I  $ -1579, $ -2134     
       SEQ.I  <    14, $ -3877     
       JMP.B  $   -15, {   -15     
       SNE.I  $ -3444, $ -3999     
       SEQ.I  <    10, $  2258     
       DJN.A  $   -18, {   -18     
       SNE.I  $   277, $  -278     
       SEQ.I  <     9, $ -2021     
       JMP.B  $   -21, }   -21     
       SNE.I  $  -690, $ -3106     
       SEQ.I  <   -16, $  3150     
       JMP.B  *    -6, {   -22     
       SNE.I  $  1169, $   614     
       SEQ.I  <   -18, $ -1130     
       JMP.B  $   -27, $  2804     
       JMP.B  $   -95, $ -3335     
       DAT.F  $    87, $ -1474     
       END
