       ORG         93
       SPL.B  $     1, <  1200     
       SPL.B  $     1, <  1500     
       SPL.B  $     1, <  1800     
       MOV.I  {    12, {     1     
       SPL.B  $ -3000, <  2100     
       MOV.I  <     2, {     1     
       DJN.F  $  -648, <  2400     
       SPL.B  $ -3712, $     8     
       MOV.I  >    -1, }    -1     
       SPL.B  $  2102, <     4     
       MOV.I  >     3, }    -1     
       MOV.I  $     3, > -3497     
       MOV.I  $     2, }  2465     
       JMZ.F  $    -4, $     4     
       DAT.F  <  2667, < -2666     
       SPL.B  #     8, <     2     
       MOV.I  #     1, <     1     
       MOV.I  $     5, $  1692     
       ADD.AB # -3902, $    -1     
       MOV.I  $    -4, @    -2     
       DJN.F  @    -3, <  3684     
       DAT.F  $     0, $     0     
       DJN.B  $    -2, #    99     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MUL.B  *     2, $     4     
       SNE.I  <    27, @     3     
       ADD.B  $     6, $     2     
       MOV.I  $    26, @     1     
       MOV.I  $    25, *  1742     
       ADD.AB #    -7, $    -1     
       DJN.B  $    -3, #    18     
       JMP.B  $   -90, $ -2416     
       DAT.F  $  4000, $  -555     
       DAT.F  $  4000, $  1306     
       SNE.I  $  3046, $ -3648     
       SEQ.I  <    -2, $  2608     
       JMP.B  $   -12, }   -10     
       SNE.I  $ -1579, $ -2134     
       SEQ.I  <    14, $ -3877     
       JMP.B  $   -15, {   -15     
       SNE.I  $ -3444, $ -3999     
       SEQ.I  <    10, $  2258     
       DJN.A  $   -18, {   -18     
       SNE.I  $   277, $  -278     
       SEQ.I  <     9, $ -2021     
       JMP.B  $   -21, }   -21     
       SNE.I  $  -690, $ -3106     
       SEQ.I  <   -16, $  3150     
       JMP.B  $   -24, {   -22     
       SNE.I  $  1169, $   614     
       SEQ.I  <   -18, $ -1130     
       JMP.B  $   -27, $  2804     
       JMP.B  $  -111, $ -3335     
       DAT.F  $    87, $ -1474     
       END
