       ORG          0
       MOV.I  $     9, $ -1668     
       MOV.I  $     9, $ -1668     
       MOV.I  $    13, $ -1629     
       MOV.I  $    13, $ -1629     
       MOV.I  {    13, <    13     
       MOV.I  {    12, <    12     
       MOV.I  {    11, <    11     
       MOV.I  {    10, <    10     
       JMP.B  @     9, {     0     
       DAT.F  $    19, $   500     
       DAT.F  $  3960, $ -3955     
       SPL.B  #    41, $    45     
       MOV.I  *   -20, >   -20     
       MOV.I  *    20, >   -20     
       DJN.F  $    -1, {   -21     
       DAT.F  #     1, $    45     
       SPL.B  #   -40, $    45     
       DAT.F  $    -2, $ -1662     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MUL.B  *     2, $     4     
       SNE.I  <    27, @     3     
       ADD.B  $     6, $     2     
       MOV.I  $    26, @     1     
       MOV.I  $    25, *  2198     
       ADD.AB #     7, $    -1     
       DJN.B  $    -3, #    21     
       DJN.F  $   -77, < -3400     
       DAT.F  $  4000, $ -1867     
       DAT.F  $  4000, $  -334     
       SNE.I  $  1862, $  1528     
       SEQ.I  <    -2, $  -672     
       JMP.B  $   -12, }   -10     
       SNE.I  $  -995, $ -2862     
       SEQ.I  <    14, $  2939     
       JMP.B  $   -15, {   -15     
       SNE.I  $ -2532, $  3601     
       SEQ.I  <    10, $  1402     
       DJN.A  $   -18, {   -18     
       SNE.I  $   533, $ -1334     
       SEQ.I  <     9, $ -3533     
       JMP.B  $   -21, }   -21     
       SNE.I  $ -1218, $  3382     
       SEQ.I  <   -16, $  1182     
       JMP.B  $   -24, {   -22     
       SNE.I  $   313, $ -1554     
       SEQ.I  <   -18, $ -3754     
       DJN.F  $   -27, <  3260     
       DJN.F  $   -98, < -3207     
       DAT.F  $   -80, $ -1674     
       END
