       ORG         72
       DAT.F  <  2667, $   800     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     1, $    15     
       SPL.B  #    63, $    15     
       DAT.F  $     0, $     0     
       SPL.B  #     0, >    -8     
       MOV.I  *    -4, >   -10     
       MOV.I  *    -5, >   -11     
       DJN.F  $    -2, }    -5     
       DAT.F  $     1, $  3762     
       DAT.F  $     1, $  2253     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  {    32, $  1199     
       SNE.I  $ -2415, $ -3468     
       SEQ.I  <    26, $ -2082     
       JMP.B  $    15, }    17     
       SNE.I  $  -194, $   262     
       SEQ.I  <    -5, $  1649     
       JMP.B  $    12, }    12     
       SNE.I  $  2359, $  2815     
       SEQ.I  <   -66, $ -3798     
       DJN.A  $     9, {     9     
       SNE.I  $   848, $  1304     
       SEQ.I  <   -68, $  2691     
       DJN.A  $     6, *     0     
       SNE.I  $   589, $  2554     
       SEQ.I  <    12, $  3940     
       JMP.B  $     3, {     5     
       SNE.I  $  -922, $  -466     
       JMZ.F  $   -79, <    10     
       MUL.B  *     2, $     4     
       SNE.I  <   -76, @     3     
       ADD.B  $     7, $     2     
       MOV.I  $   -21, @     1     
       MOV.I  $   -22, } -1388     
       SUB.AB #     7, @    -4     
       DJN.B  $    -3, #    16     
       DJN.F  $   -87, #     0     
       SPL.B  $     1, $  1965     
       SPL.B  $     1, $   456     
       SPL.B  $     1, $ -1053     
       END
