       ORG         80
       SPL.B  $     2, } -1823     
       SPL.B  $     1, } -3304     
       SPL.B  $     1, }  3215     
       MOV.I  <     1, {     1     
       JMP.B  $  2559, $    13     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     0, <   558     
       MOV.I  }    -1, >    -1     
       SPL.B  #  2579, > -2579     
       MOV.I  {  2579, { -2578     
       ADD.F  $    -2, $    -1     
       DJN.F  @     0, {    -2     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MUL.B  *     2, $     4     
       SNE.I  <    27, @     3     
       ADD.B  $     6, $     2     
       MOV.I  $    26, @     1     
       MOV.I  $    25, *  2198     
       ADD.AB #     7, $    -1     
       DJN.B  $    -3, #    21     
       DJN.F  $   -77, < -3400     
       DAT.F  $  4000, $ -1867     
       DAT.F  $  4000, $  -334     
       SNE.I  $  1862, $  1528     
       SEQ.I  <    -2, $  -672     
       JMP.B  $   -12, }   -10     
       SNE.I  $  -995, $ -2862     
       SEQ.I  <    14, $  2939     
       JMP.B  $   -15, {   -15     
       SNE.I  $ -2532, $  3601     
       SEQ.I  <    10, $  1402     
       DJN.A  $   -18, {   -18     
       SNE.I  $   533, $ -1334     
       SEQ.I  <     9, $ -3533     
       JMP.B  $   -21, }   -21     
       SNE.I  $ -1218, $  3382     
       SEQ.I  <   -16, $  1182     
       JMP.B  $   -24, {   -22     
       SNE.I  $   313, $ -1554     
       SEQ.I  <   -18, $ -3754     
       DJN.F  $   -27, <  3260     
       DJN.F  $   -98, < -3207     
       DAT.F  $   -80, $ -1674     
       END
