       ORG         13
       DAT.F  $ -1597, $  -768     
       DAT.F  $  3424, $  -251     
       DAT.F  >   -74, {    -1     
       MUL.F  @    -1, $     6     
       SNE.I  *     5, @     5     
       MUL.X  $    -4, $     4     
       SEQ.I  $    -7, *     3     
       MOV.X  $     2, $     2     
       MOV.I  $    -6, @     1     
       MOV.I  $  -704, }  1120     
       ADD.AB #     5, $    -1     
       DJN.B  $    -3, #    20     
       JMP.B  $    74, $     0     
       SEQ.I  $   951, $  -548     
       DJN.F  $    -9, $    -5     
       SEQ.I  $ -3334, $  3354     
       JMP.B  $   -11, {   -11     
       SEQ.I  $ -2632, $  2232     
       DJN.F  $   -13, {   -13     
       SEQ.I  $  1398, $  1750     
       DJN.F  $   -15, $   -19     
       SNE.I  $  -716, $  1108     
       SEQ.I  $   691, $  2867     
       JMP.B  $   -19, $     0     
       SNE.I  $ -2511, $ -1135     
       SEQ.I  $  2480, $ -2896     
       JMP.B  $   -23, $     0     
       SNE.I  $  2062, $  -887     
       SEQ.I  $ -2099, $   525     
       DJN.F  $   -26, $   -20     
       SNE.I  $ -1813, $ -2261     
       SEQ.I  $  3562, $ -3542     
       DJN.F  $   -29, $   -31     
       SNE.I  $ -3736, $  3816     
       SEQ.I  $  3687, $ -3865     
       JMP.B  $   -32, <   -33     
       SNE.I  $ -3035, $  2693     
       SEQ.I  $  2980, $  1252     
       DJN.F  $   -35, <   -36     
       JMP.B  $    47, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  {     1, {     3     
       MOV.I  $    13, <     3     
       DJN.B  $    -2, #     9     
       SPL.B  $ -1830, >     1     
       DJN.F  <     0, *  -918     
       SNE.I  $  2416, $ -3170     
       ADD.F  $     7, $    -1     
       MOV.I  $     3, >    -2     
       MOV.I  $     2, }    -3     
       DJN.B  @    -2, #   348     
       SPL.B  #     1, $     1     
       MOV.I  $     2, >    -3     
       DJN.F  $    -1, >    -4     
       DAT.F  $     8, $     8     
       END
