       ORG          0
       LDP.AB #     0, $     0     
       SEQ.AB #    -1, $    -1     
       JMP.B  $    28, $     0     
       STP.AB #     0, #    10     
       STP.AB #     0, #    11     
       STP.AB #     0, #    12     
       STP.AB #     0, #    13     
       STP.AB #     0, #    14     
       STP.AB #     0, #    15     
       STP.AB #     0, #    16     
       STP.AB #     0, #    17     
       STP.AB #     0, #    18     
       STP.AB #     0, #    19     
       STP.AB #     0, #    20     
       STP.AB #     0, #    21     
       STP.AB #     0, #    22     
       STP.AB #     0, #    23     
       STP.AB #     0, #    24     
       STP.AB #     0, #    25     
       STP.AB #     0, #    26     
       STP.AB #     0, #    27     
       STP.AB #     0, #    28     
       STP.AB #     0, #    29     
       STP.AB #     0, #    30     
       STP.AB #     0, #    31     
       STP.AB #     0, #    32     
       STP.AB #     0, #    33     
       STP.AB #     0, #    34     
       STP.AB #     0, #    35     
       STP.AB #     0, #    36     
       LDP.AB #   332, $    41     
       ADD.F  $    40, $    36     
       MUL.AB #     3, $    35     
       LDP.AB #   333, $    38     
       STP.B  $    37, #   332     
       ADD.F  $    36, $    32     
       MUL.AB #     3, $    31     
       LDP.AB #   334, $    34     
       STP.B  $    33, #   333     
       ADD.F  $    32, $    28     
       ADD.AB #    10, $    27     
       LDP.B  $    26, $    30     
       SNE.AB #     1, $   -42     
       ADD.AB #     2, $    28     
       SUB.AB #     1, $    27     
       STP.B  $    26, $    22     
       SUB.AB #    10, $    21     
       MOD.AB #     9, $    20     
       MUL.AB #     3, $    19     
       ADD.AB #    10, $    18     
       LDP.B  $    17, $    18     
       NOP.F  >    16, $     0     
       LDP.B  $    15, $    17     
       NOP.F  >    14, $     0     
       LDP.B  $    13, $    16     
       SLT.B  $    13, $    14     
       JMP.B  $     5, $     0     
       SLT.B  $    12, $    13     
       MOV.A  #    -1, $     6     
       ADD.A  #     2, $     5     
       JMP.B  $     3, $     0     
       SLT.B  $     9, $     7     
       MOV.A  #     2, $     2     
       STP.AB $     1, #   334     
       JMP.B  @     0, $    22     
       DAT.F  $     0, $    22     
       DAT.F  $     0, $    10     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  #     0, <    -3     
       MOV.I  #     4, $     1     
       END
