       ORG          1
       DAT.F  $     0, $     0     
       LDP.A  #     0, $    -1     
       LDP.A  #    13, $     4     
       ADD.A  $    -3, $     3     
       STP.AB *     2, #    13     
       NOP.F  $     1, $    33     
       JMP.B  @     0, $     0     
       DAT.F  $     7, $    21     
       DAT.F  $     4, $    31     
       DAT.F  $     1, $    29     
       DAT.F  $     1, $    28     
       DAT.F  $     7, $    17     
       DAT.F  $     4, $    27     
       DAT.F  $     1, $    25     
       DAT.F  $     9, $    14     
       DAT.F  $     7, $    13     
       DAT.F  $    11, $    23     
       DAT.F  $     9, $    11     
       DAT.F  $    14, $    20     
       DAT.F  $    11, $    20     
       DAT.F  $    11, $    19     
       DAT.F  $     9, $     7     
       DAT.F  $    14, $    16     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  #     0, <    -3     
       MOV.I  #     4, $     1     
       END
