       ORG          0
       STP.AB #    99, #   111     
       LDP.A  #     0, $    -1     
       LDP.A  #   469, $    48     
       LDP.AB #   468, $    47     
       LDP.AB #   470, $    24     
       LDP.A  #   467, $    34     
       JMZ.F  $    36, *    -6     
       LDP.AB #    13, #     0     
       LDP.AB #    18, #     0     
       ADD.BA $    -2, $     9     
       MOV.B  $    -3, $     1     
       MOD.AB #   300, #     0     
       JMN.B  $     6, $    -1     
       DIV.AB #     2, $    -6     
       LDP.AB #   117, #     0     
       SUB.B  $    -1, #     1     
       SLT.B  $    -9, $    -8     
       STP.B  $    -2, #   117     
       STP.AB #     1, #    13     
       SNE.A  #     1, $   -19     
       ADD.AB #     1, $   -12     
       STP.B  $   -13, #    18     
       LDP.AB #   117, #     0     
       JMZ.B  $     2, $    -1     
       MOV.A  #     0, $   -24     
       LDP.B  $     3, #     0     
       SUB.AB $   -26, #     1     
       ADD.B  $    -1, $    -2     
       STP.B  $    -3, #     0     
       ADD.AB *    21, $    20     
       ADD.B  @    20, $    19     
       ADD.AB $   -31, $    18     
       LDP.B  $    17, #     0     
       ADD.BA $    -1, $     6     
       MOD.A  #     3, $     5     
       STP.B  $    14, #   470     
       STP.AB $    14, #   468     
       STP.AB $   -37, #   469     
       STP.AB $     1, #   467     
       JMN.B  @     0, $    24     
       JMP.B  @     0, $    32     
       JMP.B  @     0, $    32     
       STP.AB #     1, #    13     
       STP.A  #     1, $     5     
       STP.AB #     2, $     4     
       ADD.F  #     3, $     3     
       DJN.B  $    -3, #     9     
       JMP.B  $    16, $     0     
       DAT.F  $   473, $   475     
       DAT.F  #     0, #   473     
       DAT.F  #     0, #     0     
       DAT.F  #     3, #     9     
       DAT.F  #     6, #    18     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  #     0, <    -3     
       MOV.I  #     4, $     1     
       PIN        211
       END
