       ORG         11
       JMP.B  #     0, <    -3     
       MOV.I  #     4, $     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       LDP.AB #     0, #     0     
       SLT.B  $    -1, #     3     
       JMP.B  $    21, $     0     
       LDP.AB #     1, #     0     
       MUL.AB #   621, $    -1     
       ADD.AB #     1, $    -2     
       MOD.AB #   800, $    -3     
       STP.B  $    -4, #     1     
       LDP.A  #     5, $     4     
       LDP.A  #     2, $    14     
       LDP.A  #     3, $    14     
       LDP.A  #     4, $    14     
       ADD.AB #     0, #    11     
       JMZ.B  $    27, $   -13     
       DJN.B  $     2, $   -14     
       JMP.B  $    14, $     0     
       MOV.A  #     2, $    10     
       SUB.AB $     8, #   800     
       SLT.B  $    -1, $   -15     
       MOV.A  #     1, $     7     
       SLT.AB $     3, $   -17     
       MOV.A  #     0, $     5     
       STP.AB $     4, #     5     
       STP.AB #   266, #     2     
       STP.AB #   266, #     3     
       STP.AB #   266, #     4     
       JMP.B  @     0, $   -36     
       DAT.F  $     0, $   -31     
       DAT.F  $     0, $   -39     
       SLT.A  #     1, $    -6     
       JMP.B  $   -14, $     0     
       SLT.A  #     1, $    -7     
       JMP.B  $   -16, $     0     
       SLT.A  #     1, $    -8     
       JMP.B  $   -18, $     0     
       NOP.F  {   -12, {   -11     
       NOP.F  {   -13, {   -12     
       NOP.F  {   -12, {   -12     
       ADD.A  #     6, @   -26     
       JMP.B  $   -23, $     0     
       SLT.A  #     1, @   -28     
       JMP.B  $   -25, $     0     
       NOP.F  }   -19, }   -18     
       NOP.F  }   -18, $     0     
       SUB.A  #     3, @   -32     
       JMP.B  $   -29, $     0     
       END
