       ORG          6
       JMP.B  #     0, <    -3     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       MOV.I  #     4, $     1     
       LDP.AB #     1, #     0     
       LDP.AB #     2, #     0     
       LDP.AB #     3, #     0     
       LDP.AB #     0, #     0     
       SEQ.AB #     1, $    -4     
       JMP.B  $    27, $     0     
       SEQ.AB #    18, $    -5     
       JMP.B  $     8, $     0     
       SLT.B  $    -6, #    27     
       JMP.B  $    19, $     0     
       STP.AB #     2, #     1     
       STP.AB #     1, #     2     
       STP.AB #     1, #     3     
       STP.AB #     0, #    20     
       JMP.B  $    41, $     0     
       ADD.AB #     1, $   -14     
       MOV.BA $   -15, $     1     
       STP.AB #     0, #     2     
       SEQ.AB #     1, $   -15     
       JMP.B  $     5, $     0     
       ADD.AB #     3, $   -18     
       MOV.BA $   -19, $     1     
       STP.AB #     0, #     3     
       JMP.B  $     7, $     0     
       SEQ.AB #     0, $   -21     
       ADD.A  #     1, $     1     
       MOV.A  #     0, $    -6     
       JMP.B  $    -7, $     0     
       STP.AB #     1, #     2     
       STP.AB #     1, #     3     
       MOV.BA $   -29, $    45     
       JMP.B  $    44, $     0     
       SEQ.AB #    18, $   -31     
       JMP.B  $     7, $     0     
       SLT.B  $   -32, #    27     
       JMP.B  $    18, $     0     
       STP.AB #     1, #     1     
       STP.AB #     1, #     2     
       STP.AB #     1, #     3     
       JMP.B  $   -40, $     0     
       ADD.AB #     1, $   -39     
       MOV.BA $   -40, $     1     
       STP.AB #     0, #     2     
       SEQ.AB #     1, $   -40     
       JMP.B  $     5, $     0     
       ADD.AB #     3, $   -43     
       MOV.BA $   -44, $     1     
       STP.AB #     0, #     3     
       JMP.B  $     7, $     0     
       SEQ.AB #     0, $   -46     
       ADD.A  #     1, $     1     
       MOV.A  #     0, $    -6     
       JMP.B  $    -7, $     0     
       STP.AB #     1, #     2     
       STP.AB #     1, #     3     
       LDP.A  #     0, #     1     
       LDP.A  #    20, $     4     
       ADD.A  $    -2, $     1     
       MOD.A  #    13, $     2     
       STP.B  *     1, #    20     
       JMP.B  }     0, $  1148     
       DAT.F  $   -67, $  1149     
       DAT.F  $   -68, $  1150     
       DAT.F  $   -69, $  1151     
       DAT.F  $   -69, $  1230     
       DAT.F  $   -70, $    61     
       DAT.F  $   -71, $  2012     
       DAT.F  $   -72, $   843     
       DAT.F  $   -69, $  2318     
       DAT.F  $   -70, $  2319     
       DAT.F  $   -71, $  2320     
       DAT.F  $   -72, $  2321     
       DAT.F  $   -77, $  1713     
       DAT.F  $   -79, $  1148     
       DAT.F  $   -80, $  1148     
       JMP.A  $     0, }     0     
       JMP.B  $   -77, $     0     
       JMP.B  $   -83, $     0     
       JMP.B  $   -83, $     0     
       JMP.B  $   -80, $     0     
       JMP.B  $   -85, $     0     
       JMP.B  $   -87, $     0     
       JMP.B  $   -88, $     0     
       JMP.B  $   -84, $     0     
       JMP.B  $   -89, $     0     
       JMP.B  $   -91, $     0     
       JMP.B  $   -87, $     0     
       JMP.B  $   -88, $     0     
       JMP.B  $   -94, $     0     
       JMP.B  $   -90, $     0     
       JMP.B  $   -95, $     0     
       JMP.B  $   -97, $     0     
       JMP.B  $   -93, $     0     
       JMP.B  $   -99, $     0     
       END
