       ORG          6
       JMP.B  #     0, <    -3     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       MOV.I  #     4, $     1     
       LDP.AB #     0, #     0     
       LDP.A  #     1, $     6     
       SNE.A  #    25, $     5     
       MOV.A  #     0, $     4     
       ADD.A  #     1, $     3     
       STP.AB $     2, #     1     
       JMP.B  @     1, $     0     
       JMP.A  $     0, }     0     
       JMP.B  $    -9, $     0     
       JMP.B  $   -15, $     0     
       JMP.B  $   -15, $     0     
       JMP.B  $   -12, $     0     
       JMP.B  $   -17, $     0     
       JMP.B  $   -19, $     0     
       JMP.B  $   -20, $     0     
       JMP.B  $   -16, $     0     
       JMP.B  $   -21, $     0     
       JMP.B  $   -23, $     0     
       JMP.B  $   -19, $     0     
       JMP.B  $   -20, $     0     
       JMP.B  $   -26, $     0     
       JMP.B  $   -22, $     0     
       JMP.B  $   -27, $     0     
       JMP.B  $   -29, $     0     
       JMP.B  $   -25, $     0     
       JMP.B  $   -31, $     0     
       JMP.B  $   -31, $     0     
       JMP.B  $   -32, $     0     
       JMP.B  $   -34, $     0     
       JMP.B  $   -30, $     0     
       JMP.B  $   -36, $     0     
       JMP.B  $   -32, $     0     
       JMP.B  $   -37, $     0     
       END
