       ORG         21
       JMP.B  #     0, <    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  #     4, $     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  #     0, $    13     
       LDP.A  #   278, $     3     
       MOD.BA *    11, $     2     
       STP.B  *     1, #   278     
       JMP.B  }     0, $   441     
       DAT.F  #   -14, $   154     
       DAT.F  #   -15, $   163     
       DAT.F  #   -16, $    92     
       DAT.F  #   -29, $   102     
       DAT.F  #   -24, $   446     
       DAT.F  #   -25, $   362     
       DAT.F  #   -26, $   362     
       DAT.F  #   -27, $   362     
       DAT.F  $     0, $     8     
       DAT.F  $     0, $     7     
       DAT.F  $     0, $     9     
       END
