       ORG         21
       JMP.B  #     0, <    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  #     4, $     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     3, }    -3     
       MOV.I  $     2, }    -4     
       JMP.B  $    -2, $     0     
       DAT.F  $     7, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.AB #     0, #     0     
       SNE.AB #    -1, $    -1     
       JMP.B  $     5, $     0     
       LDP.A  #     3, $     1     
       JMP.B  @     0, $     4     
       DAT.F  #     0, $     9     
       DAT.F  #     0, $    14     
       ADD.AB #     3, $    -7     
       SNE.AB #     2, $    -8     
       JMP.B  $   -24, $     0     
       SNE.AB #     0, $   -10     
       JMP.B  $     7, $     0     
       STP.AB #     1, #     3     
       JMP.B  $   -34, $     0     
       SNE.AB #     2, $   -14     
       JMP.B  $   -36, $     0     
       SNE.AB #     0, $   -16     
       JMP.B  $     5, $     0     
       STP.AB #     2, #     3     
       JMP.B  $   -28, $     0     
       SNE.AB #     2, $   -20     
       JMP.B  $   -30, $     0     
       STP.AB #     0, #     3     
       JMP.B  $   -38, $     0     
       END
