       ORG          4
       DAT.F  #     1, #     0     
       DAT.F  #     0, #     1     
       JMP.B  $    -1, $     0     
       SPL.B  $     0, $     0     
       ADD.F  $     4, $    20     
       JMZ.B  $    14, @     2     
       CMP.AB #    47, $     1     
       JMN.B  $     9, # -2169     
       JMN.B  $    28, #    12     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $   -14, @    -9     
       MOV.I  $   -14, <   -10     
       ADD.AB #     1, $   -11     
       SUB.F  $   -11, $   -12     
       JMZ.B  $   -16, @     4     
       MOV.I  $   -19, @     3     
       MOV.I  $   -19, <     2     
       ADD.AB #     1, $     1     
       JMN.B  $   -20, #  2064     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.AB #   -51, $   -29     
       MOV.AB #    45, $   -13     
       MOV.I  $     9, $   -30     
       JMP.B  $   -35, $     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       JMN.B  $    40, #     6     
       MOV.I  $     2, @     2     
       DJN.B  $    -1, $     1     
       DAT.F  #   -23, #     0     
       DAT.F  #     1, #     0     
       DAT.F  #     1, #     0     
       END
