       ORG         18
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #  2064, #     0     
       DAT.F  # -2070, #     0     
       ADD.AB #    16, $    -2     
       SUB.AB #    11, $    -2     
       CMP.I  @    -4, @    -3     
       JMP.B  $     8, $     0     
       JMN.B  $    -4, $    -6     
       ADD.AB #     1, $     4     
       MOV.I  $     3, @     3     
       MOV.I  $     3, <     3     
       JMP.B  $    -3, $     0     
       DAT.F  #     6, #     0     
       DAT.F  #    -5, #     0     
       SUB.AB #     4, $   -13     
       ADD.AB #     4, $   -13     
       MOV.I  $     7, @   -15     
       MOV.I  $     6, @   -15     
       ADD.AB #     2, $   -17     
       SUB.AB #     2, $   -17     
       DJN.B  $    -4, $     4     
       ADD.AB #    10, $     3     
       JMP.B  $   -15, $     0     
       SPL.B  $     0, $     0     
       DAT.F  #    10, #     0     
       END
