       ORG         43
       DAT.F  $   -61, $    65     
       DAT.F  $   -15, $     8     
       DAT.F  $   -15, $     9     
       SPL.B  #   -25, $    10     
       MOV.I  @     2, >    -4     
       MOV.I  @     1, >    -5     
       DJN.B  $    -2, {    -3     
       JMP.B  $    -3, {   -61     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, $   -35     
       MOV.I  <    -1, <     5     
       MOV.I  <    -2, <     4     
       MOV.I  <    -3, <     3     
       MOV.I  <    -4, <     2     
       DJN.B  $   335, #     1     
       JMP.B  $   -46, $   339     
       END
