       ORG         26
       SPL.B  $     0, <   -10     
       MOV.I  $     4, <  3813     
       MOV.I  $     3, @    -1     
       ADD.AB #  -568, @    -1     
       DJN.B  $    -3, <  -404     
       DAT.F  <   -11, <   -11     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $   222, $   -20     
       SPL.B  $     1, $   121     
       SPL.B  $     1, $   266     
       MOV.I  <    -1, <   223     
       MOV.I  <    -3, <   221     
       MOV.I  <    -5, <     1     
       JMP.B  @     0, $  2847     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $     0, <    -7     
       MOV.I  $     3, <    -8     
       DJN.B  $    -1, <    -9     
       DAT.F  #     0, #     0     
       DAT.F  <    -8, <    -8     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  <  -221, <     3     
       MOV.I  <  -223, <  -217     
       MOV.I  <  -224, <  -218     
       SPL.B  @     0, $  2502     
       SPL.B  @     0, $  2275     
       JMN.B  $  -253, <  -227     
       DAT.F  <  -222, <    -3     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     0, $  3277     
       MOV.I  $     0, $  3277     
       MOV.I  $     0, $  3277     
       MOV.I  $     0, $  3277     
       MOV.I  $     0, $  3277     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $     0, $  2666     
       ADD.AB #  3278, $    -1     
       JMP.B  @    -2, <   -10     
       END
