       ORG         78
       DAT.X  $     0, $    53     
       DAT.X  $     0, $    52     
       DAT.X  $     0, $    51     
       DAT.X  $     0, $    50     
       DAT.X  $     0, $    49     
       DAT.X  $     0, $    48     
       DAT.X  $     0, $    47     
       DAT.X  $     0, $    46     
       DAT.X  $     0, $    45     
       DAT.X  $     0, $    44     
       DAT.X  $     0, $    43     
       DAT.X  $     0, $    42     
       DAT.X  $     0, $    41     
       DAT.X  $     0, $    40     
       DAT.X  $     0, $    39     
       DAT.X  $     0, $    38     
       DAT.X  $     0, $    37     
       DAT.X  $     0, $    36     
       DAT.X  $     0, $    35     
       DAT.X  $     0, $    34     
       DAT.X  $     0, $    33     
       DAT.X  $     0, $    32     
       DAT.X  $     0, $    31     
       DAT.X  $     0, $    30     
       DAT.X  $     0, $    29     
       DAT.X  $     0, $    28     
       DAT.X  $     0, $    27     
       DAT.X  $     0, $    26     
       DAT.X  $     0, $    25     
       DAT.X  $     0, $    24     
       DAT.X  $     0, $    23     
       DAT.X  $     0, $    22     
       DAT.X  $     0, $    21     
       DAT.X  $     0, $    20     
       DAT.X  $     0, $    19     
       DAT.X  $     0, $    18     
       DAT.X  $     0, $    17     
       DAT.X  $     0, $    16     
       DAT.X  $     0, $    15     
       DAT.X  $     0, $    14     
       DAT.X  $     0, $    13     
       DAT.X  $     0, $    12     
       DAT.X  $     0, $    11     
       DAT.X  $     0, $    10     
       DAT.X  $     0, $     9     
       DAT.X  $     0, $     8     
       DAT.X  $     0, $     7     
       DAT.X  $     0, $     6     
       DAT.X  $     0, $     5     
       DAT.F  >    -1, >     1     
       SPL.B  #     0, <  -100     
       MOV.I  $    -2, $ -1499     
       ADD.AB #   197, $    -1     
       DJN.F  $    -2, < -1151     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, <  -200     
       SPL.B  $     1, <  -300     
       MOV.I  $    -1, $     0     
       SPL.B  @     0, }  1800     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, }  3740     
       MOV.I  }    -1, >    -1     
       MOV.I  { -1870, <  1870     
       MOV.I  {    -3, <     1     
       JMP.B  @     0, > -1922     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     1     
       DAT.F  $     0, $     8     
       DAT.F  $     0, $     2     
       DAT.F  $     0, $     6     
       LDP.A  #     0, $    -3     
       LDP.A  #   138, $     4     
       MOD.A  #     4, $     3     
       ADD.BA *    -6, $     2     
       STP.A  *     1, $    -3     
       JMP.A  @     0, $     0     
       DAT.F  $     0, $    11     
       DAT.F  $     1, $   -35     
       DAT.F  $     1, $   -36     
       DAT.F  $     2, $     6     
       DAT.F  $     2, $     5     
       DAT.F  $     0, $   -27     
       DAT.F  $     1, $   -40     
       DAT.F  $     0, $   -29     
       DAT.F  $     0, $   -30     
       DAT.F  $     3, $     0     
       DAT.F  $     0, $   -32     
       MOV.AB #    -4, $     1     
       DJN.B  $     0, #     0     
       DJN.B  $    -2, #    10     
       MOV.I  $   -11, $   -14     
       JMP.A  $   -17, $     0     
       END
