       ORG          0
       MOV.I  <    26, <     7     
       SPL.B  $     7, >  -200     
       MOV.I  <    24, <     5     
       MOV.I  <    23, <     4     
       MOV.I  <    22, <     3     
       MOV.I  <    21, <     2     
       MOV.I  <    20, <     1     
       JMP.B  $ -2830, # -2826     
       MOV.I  <    11, {     5     
       MOV.I  <    10, {     4     
       MOV.I  <     9, {     3     
       MOV.I  <     8, {     2     
       MOV.I  <     7, {     1     
       JMP.B  $  2727, <  -200     
       SPL.B  #     0, >     1     
       MOV.I  $     3, $     3     
       ADD.F  #  1144, $     1     
       JMP.B  $ -1143, <  -535     
       MOV.I  #  1143, *     0     
       DAT.F  $     0, $     0     
       DAT.F  > -2665, #  3600     
       DAT.F  > -2665, #    15     
       SPL.B  #     0, > -2669     
       SPL.B  #     0, > -2670     
       MOV.I  $    -3, >    -4     
       DJN.F  $    -1, >    -5     
       DAT.F  $     0, $     0     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       SPL.B  #     1, >     1     
       SPL.B  #     1, <     1     
       SPL.B  #     1, #     1     
       END
