       ORG         17
       SPL.B  $     1, < -3000     
       MOV.I  $    -1, $     0     
       MOV.I  $    -1, $     0     
       MOV.I  $    -1, $     0     
       SPL.B  @     0, <  3030     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <  2365     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <   777     
       MOV.I  }    -1, >    -1     
       MOV.I  $     2, <    -1     
       JMP.B  $    -1, <   -10     
       DAT.F  <  2667, < -2666     
       DAT.F  >    -1, >     1     
       DAT.F  $     0, $     0     
       DAT.F  $     1, $    20     
       DAT.F  $     1, $    10     
       LDP.A  #     0, $    -3     
       LDP.A  #   250, $     4     
       MOD.A  #    10, $     3     
       ADD.BA *    -6, $     2     
       STP.A  *     1, $    -3     
       JMP.B  @     0, $   -22     
       SPL.B  #     0, $    42     
       SPL.B  #     0, $    41     
       SPL.B  #     3, $    27     
       SPL.B  #     3, $    26     
       SPL.B  #     4, $    25     
       SPL.B  #     6, $    37     
       SPL.B  #     7, $   -29     
       SPL.B  #     7, $   -30     
       SPL.B  #     8, $   -31     
       SPL.B  #     1, $    33     
       SPL.B  #     2, $    32     
       SPL.B  #     3, $    18     
       SPL.B  #     3, $    17     
       SPL.B  #     4, $    16     
       SPL.B  #     5, $    15     
       SPL.B  #     0, $    27     
       SPL.B  #     7, $   -39     
       SPL.B  #     8, $   -40     
       SPL.B  #     9, $   -41     
       SPL.B  #     1, $    23     
       SPL.B  #     2, $    22     
       SPL.B  #     3, $     8     
       SPL.B  #     4, $     7     
       SPL.B  #     5, $     6     
       SPL.B  #     6, $    18     
       SPL.B  #     7, $   -48     
       SPL.B  #     8, $   -49     
       SPL.B  #     9, $   -50     
       SPL.B  #     3, $     1     
       MOV.I  $    10, <     3     
       MOV.I  $     8, <     2     
       MOV.I  $     6, <     1     
       MOV.I  $   -42, *  -100     
       SPL.B  <    -1, <  2000     
       MOV.I  $     2, @    -2     
       DIV.F  #     0, $    -3     
       SPL.B  #     0, < -1148     
       MOV.I  $   197, $ -1499     
       ADD.AB {     0, }     0     
       DJN.F  $    -2, < -1151     
       MOV.I  $     7, >    70     
       MOV.I  $     5, >    -1     
       SEQ.I  $   145, $   140     
       MOV.B  $    -1, @    -2     
       ADD.F  $     2, $    -2     
       DJN.B  $    -4, #   800     
       SPL.I  #    70, #    70     
       MOV.I  $     2, >    -6     
       DJN.F  $    -1, >    -7     
       DAT.F  <     1, #    10     
       END
