       ORG          0
       LDP.B  $     1, #     0     
       LDP.AB #   249, #     0     
       LDP.AB #   250, #     0     
       JMZ.F  $     3, >    -3     
       SLT.AB #     3, $    -2     
       JMP.B  $     5, <    -5     
       STP.AB #     2, #   253     
       STP.AB #     0, #   252     
       STP.AB #     0, #   251     
       MOV.AB #  1000, $    -8     
       JMN.B  $     2, $   -10     
       MOV.A  #     1, $     7     
       SNE.AB #     1, $   -12     
       JMP.B  $     8, $     0     
       SNE.AB #     2, $   -14     
       MOV.A  #     2, $     3     
       ADD.BA $   -14, $     1     
       LDP.AB #   251, #     0     
       ADD.AB #     0, $    -1     
       MOD.AB #     3, $    -2     
       STP.BA $    -3, $    -3     
       ADD.BA $   -21, $     1     
       LDP.AB #   251, #     0     
       MUL.AB #  2667, $    -1     
       ADD.B  $    -2, $   -23     
       STP.B  $   -25, #   250     
       STP.B  $   -25, #   249     
       SLT.AB #  2667, $   -26     
       JMP.B  $     4, $     0     
       SLT.AB # -2666, $   -28     
       JMP.B  $    14, $     0     
       JMP.B  $    45, $     0     
       MOV.I  $     9, $    -1     
       MOV.I  @    -2, <     5     
       MOV.I  <    -3, <     4     
       MOV.I  <    -4, <     3     
       MOV.I  <    -5, <     2     
       DJN.B  $    -4, $    -6     
       SPL.B  @     0, $ -3000     
       JMZ.B  $     0, <    -1     
       JMP.B  $    -8, $     0     
       DAT.F  $     0, $    12     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     1     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       DJN.B  $    -4, #     4     
       JMP.B  $   318, $    18     
       MOV.I  $    16, @     4     
       MOV.I  $    15, *     3     
       ADD.F  $    13, $     9     
       MOV.I  $     8, @     8     
       SNE.I  $   -34, $    38     
       JMP.B  $    -3, $     0     
       ADD.F  $     4, $     5     
       MOV.I  $     9, $    10     
       MOV.I  >     9, }     9     
       JMN.B  $    -1, $     8     
       JMP.B  $ -2917, $  2917     
       JMP.B  $  -199, $   200     
       MOD.X  #    10, #     1     
       STP.AB #     0, #     0     
       DJN.B  $    -1, $    -1     
       MOV.I  $     1, $    -1     
       DAT.F  $ -2924, $    15     
       DAT.F  $     0, $     0     
       DAT.F  #  -402, {  -390     
       DAT.F  #    30, {    -1     
       DAT.F  #    30, {    -1     
       SPL.B  #    30, $ -1466     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $    16, $   624     
       MOV.I  {    -1, <    -1     
       MOV.I  {    -2, <    -2     
       MOV.I  {    -3, <    -3     
       MOV.I  {    -4, <    -4     
       MOV.I  {    -5, <    -5     
       MOV.I  $   -10, $   598     
       MOV.I  {    -1, <    -1     
       MOV.I  {    -2, <    -2     
       MOV.I  {    -3, <    -3     
       JMP.B  $   610, $     0     
       SUB.F  $     1, @     1     
       SNE.I  *   -19, @   -19     
       DJN.F  $    -2, <  -823     
       SPL.B  #     0, <   -21     
       MOV.I  @     1, }   -22     
       DJN.B  $    -1, <   -20     
       END
