       ORG         65
       JMP.B  #   -86, >   673     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DJN.B  #     0, #  1402     
       DJN.B  #     0, #  1645     
       DJN.B  #     0, #  1888     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  #   152, #     0     
       MOV.I  *     0, *  -152     
       MOV.I  $    -2, @    -1     
       ADD.AB #   304, }    -2     
       JMZ.A  {    -3, $    -3     
       MOV.I  $     1, >    -1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $   -19, $ -2953     
       DAT.F  $   -20, $ -2710     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $    13, $   -10     
       SPL.B  $     2, $  3008     
       SPL.B  $     1, $ -1145     
       MOV.I  {   -13, <    -2     
       MOV.I  {   -14, <    -3     
       MOV.I  <    -5, <    -3     
       MOV.I  <    -6, <    -4     
       SPL.B  $  2999, {     0     
       DJN.A  $ -1154, #     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMZ.B  #   -29, {     0     
       SEQ.F  $     8, *    -1     
       JMP.B  $    -2, <   -35     
       SUB.A  $    -3, $     5     
       MOV.I  $     4, *    -4     
       MOV.A  #    18, $     3     
       JMP.B  $    -6, <   -39     
       DAT.F  $     0, $     0     
       JMP.B  $    18, <    -1     
       JMP.B  #     0, #     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMZ.B  #   -47, {     0     
       SNE.AB #     0, *    -1     
       MOV.I  $     2, *    -2     
       JMP.B  $    -3, <   -54     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SNE.I  $  2715, $ -3640     
       SEQ.I  <   -66, $  2251     
       JMP.B  $    25, }    25     
       SNE.I  $  -652, $   993     
       SEQ.I  <   -50, $ -1116     
       JMP.B  $    22, {    22     
       SNE.I  $  -899, $   746     
       SEQ.I  <   -54, $ -1363     
       DJN.A  $    19, {    19     
       SNE.I  $  3926, $ -2186     
       SEQ.I  <   -70, $  3704     
       JMP.B  $    16, }    18     
       SNE.I  $  3435, $ -3163     
       SEQ.I  <   -75, $  2727     
       JMP.B  $    13, {    15     
       SNE.I  $  3676, $ -2679     
       SEQ.I  <   -77, $  3211     
       JMP.B  $    10, $     0     
       SEQ.I  >    13, $  3765     
       JMP.B  $     9, <    12     
       SEQ.I  $  1259, $  2903     
       JMP.B  $     6, }     6     
       SEQ.I  $  2510, $ -3846     
       JMP.B  $     4, {     4     
       SEQ.I  $  2021, $  3665     
       DJN.A  $     2, {     2     
       JMZ.F  $   -67, $ -3155     
       MUL.B  *     2, $     4     
       SNE.I  {   -74, @     3     
       ADD.B  $   -90, $     2     
       MOV.I  $   -95, @     1     
       MOV.I  $   -96, }  2108     
       SUB.AB #    -7, $    -1     
       DJN.B  $    -3, #    19     
       JMP.B  $   -75, #     0     
       END
