       ORG         69
       MOV.AB #     9, @     0     
       MOV.AB #     0, $    35     
       SUB.AB #  2049, $     6     
       MOV.I  $     5, <     5     
       JMZ.B  $    -1, @    -3     
       MOV.I  <    -5, <     2     
       JMN.B  $    -1, $    -6     
       JMP.B  @     0, $  2049     
       DAT.F  <  2667, <  -500     
       DAT.F  #    -1, <     1     
       DAT.F  #    -2, <     1     
       DAT.F  #    -3, <     1     
       DAT.F  #    -4, <     1     
       DAT.F  #    -5, <     1     
       DAT.F  #    -6, <     1     
       DAT.F  #    -7, <     1     
       DAT.F  #    -8, <     1     
       DAT.F  #    -9, <     1     
       DAT.F  #   -10, <     1     
       DAT.F  #   -11, <     1     
       DAT.F  #   -12, <     1     
       DAT.F  #   -13, <     1     
       DAT.F  #   -14, <     1     
       DAT.F  #   -15, <     1     
       DAT.F  #   -16, <     1     
       DAT.F  #   -17, <     1     
       DAT.F  #   -18, <     1     
       DAT.F  #   -19, <     1     
       DAT.F  #   -20, <     1     
       DAT.F  #   -21, <     1     
       DAT.F  #   -22, <     1     
       DAT.F  #   -23, <     1     
       DAT.F  #   -24, <     1     
       DAT.F  #   -25, <     1     
       DAT.F  #   -26, <     1     
       DAT.F  #   -27, <     1     
       DAT.F  #   -28, <     1     
       DAT.F  #   -29, <     1     
       DAT.F  #   -30, <     1     
       DAT.F  #   -31, <     1     
       DAT.F  #   -32, <     1     
       DAT.F  #   -33, <     1     
       DAT.F  #   -34, <     1     
       DAT.F  #   -35, <     1     
       DAT.F  #   -36, <     1     
       DAT.F  #   -37, <     1     
       DAT.F  #   -38, <     1     
       DAT.F  #   -39, <     1     
       DAT.F  #   -40, <     1     
       DAT.F  #   -41, <     1     
       DAT.F  #   -42, <     1     
       DAT.F  #   -43, <     1     
       DAT.F  #   -44, <     1     
       DAT.F  #   -45, <     1     
       DAT.F  #   -46, <     1     
       DAT.F  #   -47, <     1     
       DAT.F  #   -48, <     1     
       DAT.F  #   -49, <     1     
       DAT.F  #   -50, <     1     
       DAT.F  #   -51, <     1     
       DAT.F  #   -52, <     1     
       DAT.F  #   -53, <     1     
       DAT.F  #   -54, <     1     
       DAT.F  #   -55, <     1     
       DAT.F  #   -56, <     1     
       DAT.F  #   -57, <     1     
       DAT.F  #   -58, <     1     
       DAT.F  #   -59, <     1     
       DAT.F  #   -60, <     1     
       MOV.I  <     5, <     6     
       MOV.I  <     4, <     5     
       MOV.I  <     3, <     4     
       MOV.I  <     2, <     3     
       MOV.I  <     1, <     2     
       JMN.B  $    -4, $   -65     
       DJN.B  $ -1097, # -1088     
       END
