       ORG        153
       DAT.F  $    18, $   187     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.BA $    -3, $    -3     
       MOV.AB #    -6, $     2     
       ADD.B  $    -5, $     1     
       MOV.X  @     0, @     0     
       MOV.B  @    -1, $    -1     
       MOV.I  $    16, <    -8     
       MOV.I  >    -9, >    -9     
       JMN.F  $    -2, >   -10     
       ADD.BA $    -5, $   -11     
       JMZ.F  $     4, *   -12     
       MOV.AB $   -13, $   -13     
       SLT.B  $   -14, #    32     
       JMN.F  $    -7, @   -15     
       MOD.AB # 18470, $   -16     
       ADD.AB #    13, $   -17     
       JMZ.F  $    -1, @   -18     
       MOD.AB # 18470, $   -19     
       SLT.B  $   -20, #    37     
       JMZ.F  $   -18, $   -20     
       DJN.B  $    -5, #     9     
       SPL.B  #     0, #     0     
       SPL.B  #     0, #     0     
       MOV.I  $     4, <    -2     
       MOV.I  $     3, >    -5     
       MOV.I  $     2, >    -6     
       DJN.F  $    -2, >    -7     
       DAT.F  $     0, $    10     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       STP.AB #    -1, #  2026     
       SPL.B  $     1, {  3785     
       MOV.I  {     0, #     0     
       MOV.I  {     0, #     0     
       MOV.I  {     0, #     0     
       SPL.B  $     1, {  9623     
       SPL.B  @     0, { 16211     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, { 21445     
       MOV.I  }    -1, >    -1     
       SPL.B  #     0, $     0     
       ADD.F  #-19567, $     1     
       JMP.B  $ 19567, { 12087     
       MOV.I  #-19567, *     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     1, $    17     
       SPL.B  # 16135, $    17     
       MOV.I  }    28, #     0     
       MOV.I  $-16130, * 16138     
       ADD.F  $     4, $    -1     
       MOV.I  $    -4, *    -2     
       MOV.I  }    24, @    -3     
       JMN.A  $    -4, {    23     
       SPL.B  # -7038, < -7038     
       MOV.I  *    -9, >   -12     
       MOV.I  *   -10, >   -13     
       DJN.F  $    -2, }   -10     
       MOV.I  $-16134, }-16134     
       LDP.A  #     0, $    12     
       LDP.A  #  2031, $     3     
       MOD.BA *    10, $     2     
       STP.B  *     1, #  2031     
       JMP.B  }     0, $    99     
       SPL.B  #    27, $   387     
       SPL.B  #    26, $   171     
       SPL.B  #    18, $   480     
       SPL.B  #    17, $   264     
       SPL.B  #    16, $    48     
       SPL.B  #     5, $   447     
       SPL.B  #     4, $   384     
       SPL.B  #    20, $     8     
       SPL.B  #     0, $     9     
       DAT.F  $     0, $     7     
       MOV.I  <     7, {     7     
       MOV.I  @     6, {     7     
       MOV.I  <     5, {     5     
       MOV.I  @     4, {     5     
       MOV.I  <     3, {     3     
       MOV.I  @     2, {     3     
       DJN.B  $    -6, #    10     
       SPL.B  * 18335, $  -145     
       SPL.B  *-18626, $     0     
       JMP.B  $  -159, $     0     
       MOV.I  $   -26, $  9355     
       SPL.B  $     2, { 17843     
       SPL.B  $     1, { 18326     
       SPL.B  $     1, { 13965     
       MOV.I  {    -4, <     2     
       MOV.I  {    -5, <     1     
       JMP.B  >  9320, $  9330     
       SPL.B  $  -145, {  5465     
       STP.AB #    -1, #  2036     
       SPL.B  $     1, {  9753     
       MOV.I  {     0, #     0     
       MOV.I  {     0, #     0     
       MOV.I  {     0, #     0     
       SPL.B  $     1, {  4366     
       SPL.B  @     0, { 16211     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, { 21445     
       MOV.I  }    -1, >    -1     
       SPL.B  #     0, $     0     
       ADD.F  #-19567, $     1     
       JMP.B  $ 19567, { 12087     
       MOV.I  #-19567, *     0     
       END
