       ORG         47
       MOV.I  }     4, >  6000     
       MOV.I  $     6, >    -1     
       ADD.F  $     5, $     1     
       SNE.I  $   266, $   287     
       DJN.F  $    -2, < 16616     
       MOV.AB $    -2, $    -5     
       JMN.B  {    -2, $    -6     
       SPL.B  #   266, #   266     
       MOV.I  $     3, >   -11     
       DJN.F  $    -1, >   -12     
       DAT.F  $     0, $     0     
       DAT.F  >-27719, $    16     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     1, $   -13     
       MOV.I  <    -1, <   115     
       MOV.I  <    -2, <   114     
       MOV.I  <    -3, <   113     
       MOV.I  <    -4, <   112     
       MOV.I  <    -5, <   111     
       MOV.I  <    -6, <   110     
       DJN.B  $ -8028, #     2     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  #     0, $    15     
       LDP.A  #  1278, $     3     
       MOD.BA *    13, $     2     
       STP.B  *     1, #  1278     
       JMP.B  }     0, $   748     
       DAT.F  #   -27, $   210     
       DAT.F  #   -28, $   662     
       DAT.F  #    76, $   949     
       DAT.F  #    75, $   213     
       DAT.F  #    74, $   225     
       DAT.F  #   -32, $   556     
       DAT.F  #    72, $   227     
       DAT.F  #   -34, $   558     
       DAT.F  #    70, $   669     
       DAT.F  #   -36, $   430     
       DAT.F  $     0, $     9     
       DAT.F  $     0, $    10     
       DAT.F  $     0, $    11     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  <     9, {     9     
       MOV.I  <     8, {     8     
       MOV.I  <     7, {     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  $    32, $ 27052     
       MOV.I  $    12, $  -188     
       MOV.I  $    11, $ 27531     
       SPL.B  $ 27059, $    39     
       SPL.B  *    -1, >  4000     
       SPL.B  $     1, $ -8128     
       SPL.B  $     1, >  5000     
       SPL.B  $     1, >  6000     
       SPL.B  $     1, >  7000     
       SPL.B  $     1, >  8000     
       SPL.B  $     2, >  9000     
       JMP.B  $  -198, }     0     
       JMP.B  $ 27521, }     0     
       MOV.I  #     0, $-27719     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  >     0, $  1000     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, }    -4     
       SPL.B  #     0, }    -5     
       MOV.I  $     3, >    -6     
       MOV.I  $     2, >    -7     
       DJN.F  $    -1, >    -8     
       DAT.F  $  -500, $    11     
       END
