       ORG          0
       SPL.B  $     1, $     0     
       DAT.F  $     0, $     0     
       SUB.AB #     1, #    64     
       SPL.B  $    -1, $    -2     
       MOV.I  $    -3, <    -1     
       MOV.I  $    -4, <    -2     
       JMN.B  $    -3, $    -4     
       DAT.F  $     2, $    -2     
       MOV.I  $     4, $    -4     
       MOV.I  $     8, $    -8     
       MOV.I  $    16, $   -16     
       CMP.I  $    32, $   -32     
       CMP.I  $    64, $   -64     
       MOV.I  $    64, $   -64     
       JMP.B  $   -26, $    11     
       MOV.I  $     6, $     2     
       ADD.F  $    11, $     1     
       MOV.AB #     9, $    21     
       JMP.B  $    15, $    -5     
       JMZ.B  $     5, $     4     
       ADD.F  @    -2, $     1     
       CMP.I  $    96, $   -96     
       JMP.B  $    -7, <     1     
       DJN.B  $    -3, #    16     
       SUB.AB #     1, $    -6     
       MOV.I  $   -14, $    -4     
       ADD.F  <     5, $    -5     
       ADD.F  $     5, $     5     
       ADD.F  $     4, $    -5     
       DJN.B  $    -8, #     6     
       MOV.AB #   -19, $   -13     
       JMP.B  $     8, $   -19     
       MOV.AB #     0, $     8     
       MOV.I  $   -19, $   -16     
       CMP.I  $   -33, @   -13     
       JMP.B  $     8, $     0     
       SUB.F  $   -15, $   -19     
       MOV.I  $   -20, @   -20     
       MOV.AB #     7, #     7     
       MOV.I  $   -39, <   -22     
       MOV.I  $   -40, <   -23     
       DJN.B  $    -2, $    -3     
       JMP.B  $   -23, $     0     
       ADD.F  $   -22, $   -26     
       JMP.B  $    -7, $     0     
       END
