       ORG          0
       MOV.I  $    65, @ -2304     
       MOV.I  $    64, @ -2817     
       MOV.I  $    63, @ -3330     
       MOV.I  $    62, @ -3843     
       MOV.I  $    61, @  3644     
       MOV.I  $    60, @  3131     
       MOV.I  $    59, @  2618     
       JMZ.B  $     4, $ -2312     
       MOV.AB # -1899, $    96     
       DJN.B  $    73, @    -2     
       JMP.B  $    24, $     0     
       JMZ.B  $     4, $ -2828     
       MOV.AB # -2411, $    92     
       DJN.B  $    69, @    -2     
       JMP.B  $    20, $     0     
       JMZ.B  $     4, $ -3344     
       MOV.AB # -2923, $    88     
       DJN.B  $    65, @    -2     
       JMP.B  $    16, $     0     
       JMZ.B  $     4, $ -3860     
       MOV.AB # -3435, $    84     
       DJN.B  $    61, @    -2     
       JMP.B  $    12, $     0     
       JMZ.B  $     4, $  3624     
       MOV.AB # -3947, $    80     
       DJN.B  $    57, @    -2     
       JMP.B  $     8, $     0     
       JMZ.B  $     4, $  3108     
       MOV.AB #  3541, $    76     
       DJN.B  $    53, @    -2     
       JMP.B  $     4, $     0     
       JMZ.B  $     3, $  2592     
       MOV.AB #  3029, $    72     
       DJN.B  $    49, @    -2     
       MOV.AB #   -11, $    32     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       MOV.I  $    24, $ -3904     
       JMP.B  $ -3917, $     0     
       JMP.B  $    18, $     0     
       DAT.F  #     0, $     0     
       SPL.B  $    16, $     0     
       MOV.I  $     3, <    19     
       MOV.I  $     2, <    18     
       JMP.B  $    -3, $     0     
       DAT.F  #     0, $   -23     
       JMP.B  @     0, $     0     
       MOV.I  $    -1, @     3     
       SUB.F  $     2, @     2     
       SUB.AB #    20, $     1     
       JMZ.B  $    -1, $    -2     
       CMP.AB #    -2, $    -1     
       JMP.B  $    -5, $     0     
       MOV.AB #    -7, $    -8     
       MOV.I  $    -9, <     7     
       JMP.B  $    -1, $     0     
       DAT.F  #     0, $     0     
       DJN.B  $   -16, $     2     
       MOV.I  $     1, $   -17     
       DAT.F  #     0, $    64     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $   700     
       MOV.AB #    -2, $    21     
       MOV.I  $    20, <    21     
       MOV.I  $    18, <    20     
       MOV.I  $    16, <    19     
       MOV.I  $    14, <    18     
       MOV.I  $    12, <    17     
       MOV.I  $    10, <    16     
       MOV.I  $     8, <    15     
       MOV.I  $     6, <    14     
       MOV.I  $     4, <    13     
       MOV.I  $     2, <    12     
       JMP.B  @    11, $     0     
       MOV.I  @     8, <     4     
       MOV.I  @     4, <     3     
       DJN.B  $    -2, $     2     
       DAT.F  #     0, $    -6     
       DAT.F  #     0, $  -114     
       DAT.F  #     0, $     2     
       DAT.F  #     0, $    -2     
       SPL.B  $     0, $     0     
       DAT.F  #     0, $     1     
       JMP.B  $    -1, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       DAT.F  #     0, $     0     
       END
