       ORG         79
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       NOP.F  }     1, >     1     
       MOV.I  $     1, $     1     
       JMP.B  $    -1, >    -1     
       DAT.F  $     1, $     1     
       END
