       ORG          3
       DAT.F  <     0, <    59     
       DAT.F  <     0, <     0     
       DAT.F  <     0, <    25     
       MOV.I  $    56, $    17     
       MOV.I  $    28, $    35     
       SPL.B  $    28, $     0     
       MOV.AB #   810, $    25     
       MOV.AB #  -810, $    23     
       MOV.AB #    25, $    -6     
       MOV.I  @    -7, <    22     
       MOV.I  @    -8, <    20     
       DJN.B  $    -2, $    -9     
       MOV.AB #   810, $    19     
       MOV.AB #  -810, $    17     
       MOV.AB #    25, $   -12     
       CMP.I  <    16, <    15     
       JMP.B  $     5, $     0     
       CMP.I  @   -15, @    14     
       JMP.B  $    10, $     0     
       DJN.B  $    -4, $   -17     
       JMP.B  $    -8, $     0     
       MOV.I  $    36, $    18     
       MOV.AB #    59, $   -22     
       MOV.AB # -2000, $     8     
       MOV.I  @   -24, <     7     
       DJN.B  $    -1, $   -25     
       ADD.AB #     2, $     5     
       JMP.B  @     4, $     0     
       MOV.I  @     3, @   -26     
       MOV.I  $     2, $    -9     
       JMP.B  $   -11, $     0     
       JMP.B  $     1, $     0     
       JMP.B  $    -5, $     0     
       MOV.AB #   800, $    16     
       ADD.AB #    10, $    15     
       JMZ.B  $    -1, @    14     
       SUB.F  $    13, $    22     
       ADD.AB #     1, $    21     
       MOV.I  $    20, @    11     
       JMP.B  $    -5, $     0     
       MOV.I  $    17, $   -19     
       MOV.AB #     0, $   -39     
       MOV.I  $   -40, $ -3000     
       MOV.I  $   -41, <   -42     
       MOV.I  $    13, @     3     
       ADD.AB #     5, $     2     
       JMN.B  $     2, $ -3004     
       JMP.B  $    -4, #    25     
       MOV.AB #    25, $    -1     
       JMP.B  $    -7, $     0     
       MOV.I  $   -19, $   -11     
       DJN.B  $     1, $     6     
       SPL.B  $    -2, $     0     
       MOV.I  $   -51, <   -52     
       MOV.I  $     3, $   -33     
       JMN.B  $    -3, $     2     
       MOV.I  $     1, $    -4     
       DAT.F  <     0, <    64     
       JMP.B  @     0, $     0     
       JMP.B  $    -8, $     0     
       END
