       ORG          0
       SPL.B  $    13, $     0     
       MOV.I  $     4, $    61     
       ADD.AB #     1, $    -1     
       DJN.B  $    -2, $     1     
       DAT.F  <     0, <   257     
       JMP.B  $   -37, $     0     
       DAT.F  <     0, <     0     
       DAT.F  <     0, <     0     
       MOV.I  $     3, $    -2     
       JMP.B  $    -1, <    -3     
       JMP.B  $  -102, #     2     
       DAT.F  <     0, <     0     
       DAT.F  <     0, #    77     
       ADD.AB #   102, $     1     
       MOV.I  $    -4, $     9     
       DJN.B  $    -2, $    -3     
       SUB.AB #  -155, $    -2     
       MOV.AB #    77, $    -5     
       DJN.B  $    -5, $     3     
       SPL.B  $     5, $     0     
       JMP.B  $   -12, $     0     
       DAT.F  <     0, <    34     
       DAT.F  <     0, <   -16     
       MOV.I  $   -12, <    -1     
       SPL.B  $    -1, $     0     
       MOV.I  $   -14, <    -3     
       MOV.I  $   -15, <    -4     
       JMP.B  $    -4, $     0     
       JMP.B  $    -4, $     0     
       JMP.B  $    -5, $     0     
       JMP.B  $    -6, $     0     
       JMP.B  $    -7, $     0     
       JMP.B  $    -8, $     0     
       JMP.B  $    -9, $     0     
       JMP.B  $   -10, $     0     
       JMP.B  $   -11, $     0     
       JMP.B  $   -12, $     0     
       JMP.B  $   -13, $     0     
       JMP.B  $   -14, $     0     
       JMP.B  $   -15, $     0     
       JMP.B  $   -16, $     0     
       JMP.B  $   -17, $     0     
       JMP.B  $   -18, $     0     
       JMP.B  $   -19, $     0     
       JMP.B  $   -20, $     0     
       JMP.B  $   -21, $     0     
       JMP.B  $   -22, $     0     
       JMP.B  $   -23, $     0     
       JMP.B  $   -24, $     0     
       JMP.B  $   -25, $     0     
       JMP.B  $   -26, $     0     
       JMP.B  $   -27, $     0     
       JMP.B  $   -28, $     0     
       JMP.B  $   -29, $     0     
       JMP.B  $   -30, $     0     
       JMP.B  $   -31, $     0     
       JMP.B  $   -32, $     0     
       JMP.B  $   -33, $     0     
       JMP.B  $   -34, $     0     
       JMP.B  $   -35, $     0     
       JMP.B  $   -36, $     0     
       JMP.B  $   -37, $     0     
       JMP.B  $   -38, $     0     
       END
