       ORG          0
       SPL.B  $     1, $     1     
       MOV.I  $    -1, $     0     
       MOV.I  $    -1, $     0     
       SPL.B  $    46, $     0     
       SPL.B  $    32, $     0     
       SPL.B  $    18, $     0     
       JMP.B  $     4, $     0     
       DAT.F  <     0, <     5     
       MOV.AB #    10, $    10     
       SUB.F  <   203, $   204     
       MOV.I  <    -2, <     4     
       MOV.I  <    -3, <     3     
       SPL.B  $     3, $     3     
       MOV.I  $     4, <   200     
       JMZ.B  @     0, $ -1899     
       JMZ.B  $    -7, $    -7     
       MOV.I  $     0, $    -1     
       DAT.F  <     0, <   -10     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       MOV.AB #    10, $    10     
       ADD.F  <   203, $   204     
       MOV.I  <    -2, <     4     
       MOV.I  <    -3, <     3     
       SPL.B  $     3, $     3     
       MOV.I  $     4, <   200     
       JMZ.B  @     0, $ -1699     
       JMZ.B  $    -7, $    -7     
       MOV.I  $     0, $    -1     
       DAT.F  <     0, <   -10     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       MOV.AB #    10, $    10     
       SUB.F  <   203, $   204     
       MOV.I  <    -2, <     4     
       MOV.I  <    -3, <     3     
       SPL.B  $     3, $     3     
       MOV.I  $     4, <   200     
       JMZ.B  @     0, $ -1499     
       JMZ.B  $    -7, $    -7     
       MOV.I  $     0, $    -1     
       DAT.F  <     0, <   -10     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       DAT.F  <     0, <     1     
       MOV.AB #    10, $    10     
       ADD.F  <   203, $   204     
       MOV.I  <    -2, <     4     
       MOV.I  <    -3, <     3     
       SPL.B  $     3, $     3     
       MOV.I  $     4, <   200     
       JMZ.B  @     0, $ -1299     
       JMZ.B  $    -7, $    -7     
       MOV.I  $     0, $    -1     
       DAT.F  <     0, <   -10     
       END
