       ORG          0
       SPL.B  $    16, $     0     
       SPL.B  $    27, $     0     
       SPL.B  $    38, $     0     
       SPL.B  $    49, $     0     
       SPL.B  $    16, $     0     
       SPL.B  $    27, $     0     
       SPL.B  $    38, $     0     
       SPL.B  $    49, $     0     
       SPL.B  $    16, $     0     
       SPL.B  $    27, $     0     
       SPL.B  $    38, $     0     
       SPL.B  $    49, $     0     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  -512     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -1536     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -1024     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -2048     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -2560     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -3584     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, < -3072     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  3904     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  2880     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  3320     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  2368     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  1344     
       ADD.AB #   -28, $     3     
       MOV.I  $     2, @     2     
       JMP.B  $    -2, $     0     
       DAT.F  <     0, <  1856     
       END
