       ORG          4
       DAT.F  #     0, #  1588     
       DAT.F  #     0, #  1337     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  1589, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  1674     
       DAT.F  #     0, #  1423     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  1675, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  1760     
       DAT.F  #     0, #  1509     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  1761, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  1846     
       DAT.F  #     0, #  1595     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  1847, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  1932     
       DAT.F  #     0, #  1681     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  1933, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2018     
       DAT.F  #     0, #  1767     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2019, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2104     
       DAT.F  #     0, #  1853     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2105, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2190     
       DAT.F  #     0, #  1939     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2191, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2276     
       DAT.F  #     0, #  2025     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2277, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2362     
       DAT.F  #     0, #  2111     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2363, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2448     
       DAT.F  #     0, #  2197     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2449, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2534     
       DAT.F  #     0, #  2283     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2535, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2620     
       DAT.F  #     0, #  2369     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2621, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2706     
       DAT.F  #     0, #  2455     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2707, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2792     
       DAT.F  #     0, #  2541     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2793, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2878     
       DAT.F  #     0, #  2627     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2879, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  2964     
       DAT.F  #     0, #  2713     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  2965, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3050     
       DAT.F  #     0, #  2799     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3051, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3136     
       DAT.F  #     0, #  2885     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3137, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3222     
       DAT.F  #     0, #  2971     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3223, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3308     
       DAT.F  #     0, #  3057     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3309, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3394     
       DAT.F  #     0, #  3143     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3395, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3480     
       DAT.F  #     0, #  3229     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3481, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3566     
       DAT.F  #     0, #  3315     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3567, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3652     
       DAT.F  #     0, #  3401     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3653, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3738     
       DAT.F  #     0, #  3487     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3739, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3824     
       DAT.F  #     0, #  3573     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3825, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3910     
       DAT.F  #     0, #  3659     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3911, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  3996     
       DAT.F  #     0, #  3745     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  3997, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3918     
       DAT.F  #     0, #  3831     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3917, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3832     
       DAT.F  #     0, #  3917     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3831, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3746     
       DAT.F  #     0, # -3997     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3745, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3660     
       DAT.F  #     0, # -3911     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3659, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3574     
       DAT.F  #     0, # -3825     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3573, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3488     
       DAT.F  #     0, # -3739     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3487, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3402     
       DAT.F  #     0, # -3653     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3401, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3316     
       DAT.F  #     0, # -3567     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3315, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3230     
       DAT.F  #     0, # -3481     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3229, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3144     
       DAT.F  #     0, # -3395     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3143, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -3058     
       DAT.F  #     0, # -3309     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -3057, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2972     
       DAT.F  #     0, # -3223     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2971, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2886     
       DAT.F  #     0, # -3137     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2885, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2800     
       DAT.F  #     0, # -3051     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2799, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2714     
       DAT.F  #     0, # -2965     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2713, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2628     
       DAT.F  #     0, # -2879     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2627, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2542     
       DAT.F  #     0, # -2793     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2541, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2456     
       DAT.F  #     0, # -2707     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2455, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2370     
       DAT.F  #     0, # -2621     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2369, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2284     
       DAT.F  #     0, # -2535     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2283, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2198     
       DAT.F  #     0, # -2449     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2197, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2112     
       DAT.F  #     0, # -2363     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2111, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -2026     
       DAT.F  #     0, # -2277     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -2025, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1940     
       DAT.F  #     0, # -2191     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1939, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1854     
       DAT.F  #     0, # -2105     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1853, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1768     
       DAT.F  #     0, # -2019     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1767, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1682     
       DAT.F  #     0, # -1933     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1681, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1596     
       DAT.F  #     0, # -1847     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1595, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1510     
       DAT.F  #     0, # -1761     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1509, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1424     
       DAT.F  #     0, # -1675     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1423, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1338     
       DAT.F  #     0, # -1589     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1337, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1252     
       DAT.F  #     0, # -1503     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1251, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1166     
       DAT.F  #     0, # -1417     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1165, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, # -1080     
       DAT.F  #     0, # -1331     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB # -1079, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       DAT.F  #     0, #  -994     
       DAT.F  #     0, # -1245     
       DAT.F  #     0, #   123     
       SPL.B  $     0, $     0     
       SPL.B  $    17, $     0     
       CMP.I  <    -5, <    -4     
       MOV.I  $    -3, @    -6     
       CMP.I  <    -7, <    -6     
       MOV.I  $    -5, @    -7     
       DJN.B  $    -4, $    -7     
       MOV.AB #  -993, $   -10     
       MOV.AB #   168, $    -9     
       MOV.I  $   -12, <   -12     
       MOV.I  $   -13, <   -13     
       MOV.I  $   -14, <   -14     
       DJN.B  $    -3, $   -13     
       JMP.B  $    -6, $     0     
       END
