       ORG          0
       MOV.I  <    11, <    12     
       MOV.I  <    10, <    11     
       MOV.I  <     9, <    10     
       MOV.I  <     8, <     9     
       MOV.I  <     7, <     8     
       MOV.I  <     6, <     7     
       MOV.I  <     5, <     6     
       MOV.I  <     4, <     5     
       MOV.I  <     3, <     4     
       MOV.I  <     2, <     3     
       MOV.I  $    13, $  2527     
       JMP.B  $  2503, $    12     
       DAT.F  #     0, #  2511     
       ADD.AB # -3144, $     2     
       MOV.I  $     6, @     1     
       JMZ.B  $    -2, @ -3123     
       MOV.I  $    -1, @     2     
       MOV.I  $     5, @   -22     
       MOV.I  $     2, <   -23     
       JMN.B  $    -6, $    -3     
       SPL.B  $     0, <   -20     
       MOV.I  $    16, <    -5     
       JMP.B  $    -1, $     0     
       DAT.F  <   -21, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       DAT.F  #     0, #     1     
       END
