       ORG          0
       MOV.I  $    40, $  1031     
       MOV.I  $    38, <    -1     
       MOV.I  $    36, <    -2     
       MOV.I  $    37, $  2029     
       MOV.I  $    35, <    -1     
       MOV.I  $    33, <    -2     
       MOV.I  $    34, $  3029     
       MOV.I  $    32, <    -1     
       MOV.I  $    30, <    -2     
       MOV.I  $    31, $ -3973     
       MOV.I  $    29, <    -1     
       MOV.I  $    27, <    -2     
       MOV.I  $    28, $ -2973     
       MOV.I  $    26, <    -1     
       MOV.I  $    24, <    -2     
       MOV.I  $    25, $ -1975     
       MOV.I  $    23, <    -1     
       MOV.I  $    21, <    -2     
       MOV.I  $    22, $  -975     
       MOV.I  $    20, <    -1     
       MOV.I  $    18, <    -2     
       SPL.B  $     4, $     0     
       SPL.B  $     6, $     0     
       SPL.B  $     9, $     0     
       JMP.B  @   -24, $     0     
       SPL.B  $     5, $     0     
       SPL.B  $     8, $     0     
       JMP.B  @   -24, $     0     
       SPL.B  $     5, $     0     
       JMP.B  @   -23, $     0     
       SPL.B  $     5, $     0     
       JMP.B  @   -22, $     0     
       JMP.B  @   -20, $     0     
       JMP.B  @   -18, $     0     
       JMP.B  @   -16, $     0     
       JMP.B  $     3, $     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $     0, <    -2     
       MOV.I  $    -3, <    -3     
       DJN.B  $    -2, <    -4     
       END
