       ORG          7
       DAT.F  #  3438, # -3438     
       SPL.B  $     0, $     0     
       SUB.F  $    -2, $     1     
       MOV.I  <     0, $     0     
       JMP.B  $    -2, $     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $    32, $  1397     
       SPL.B  $     1, $     0     
       SPL.B  $    16, $     0     
       SPL.B  $     8, $     0     
       SPL.B  $     4, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $    26, $     0     
       JMP.B  $  2756, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $ -2707, $     0     
       JMP.B  $    23, $     0     
       SPL.B  $     4, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $  2751, $     0     
       JMP.B  $ -2711, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $    16, $  1365     
       JMP.B  $ -4081, $     0     
       SPL.B  $     8, $     0     
       SPL.B  $     4, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $ -1354, $     0     
       JMP.B  $  1376, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $ -4087, $     0     
       JMP.B  $ -1357, $     0     
       SPL.B  $   -32, $     0     
       SPL.B  $   -33, $     0     
       SPL.B  $   -34, $     0     
       SPL.B  $   -35, $     0     
       SPL.B  $   -36, $     0     
       DAT.F  #     0, #     0     
       MOV.I  $     0, $  2731     
       END
