       ORG          0
       SPL.B  $    51, $     0     
       SPL.B  $    50, $     0     
       SPL.B  $    49, $     0     
       SPL.B  $    48, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $    22, $     0     
       JMP.B  $    21, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #   693, #  -693     
       ADD.F  $    -1, $     1     
       MOV.I  <    10, $   -10     
       DJN.F  $    -2, < -3000     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     4, $     0     
       SPL.B  $     2, $     0     
       JMP.B  $     4, $     0     
       JMP.B  $  2670, $     0     
       JMP.B  $     1, $     0     
       JMP.B  $ -2665, $     0     
       MOV.I  $     0, $  2667     
       END
