       ORG         10
       SPL.B  #     1, }     1     
       MOV.I  $    -1, {    -5     
       MOV.I  }    -6, }    -6     
       JMN.F  $    -2, }    -7     
       ADD.A  #     8, @    -1     
       JMZ.F  $    -1, {    -9     
       SLT.AB @    -3, #    16     
       JMP.B  $    -6, {   -11     
       DJN.B  $    -4, #    17     
       JMP.B  $    -5, {    -8     
       MOV.I  $    -1, @    11     
       MOV.I  $    -3, <    10     
       MOV.I  $    -5, <     9     
       MOV.I  $    -7, <     8     
       MOV.I  $    -9, <     7     
       MOV.I  $   -11, <     6     
       MOV.I  $   -13, <     5     
       MOV.I  $   -15, <     4     
       MOV.I  $   -17, <     3     
       MOV.I  $   -19, <     2     
       ADD.AB #     5, $     1     
       JMP.B  @     0, $  1000     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       DAT.F  >     0, >     0     
       END
