       ORG          0
       SPL.B  $     5, $     0     
       JMP.B  $    34, $     0     
       SNE.I  $    18, @     2     
       JMP.B  $    11, $     0     
       ADD.AB #    50, # -3950     
       JMZ.F  $    -1, @    -1     
       JMN.F  $     0, <    -2     
       JMP.B  $    -5, >    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  >     5, >   -10     
       DJN.B  $    -1, #     6     
       NOP.F  $     0, $     0     
       NOP.F  $     0, $     0     
       MOV.I  $     2, $    16     
       JMP.B  <   -15, $     7     
       DAT.F  <     1, $    12     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     2, $     6     
       DAT.F  $     1, $     6     
       SPL.B  #     1, $     6     
       ADD.AB #  1141, $    -3     
       MOV.I  *    -4, >    -4     
       JMP.B  $    -2, >    -5     
       SNE.I  $    18, @     2     
       JMP.B  $    11, $     0     
       ADD.AB #    50, #   150     
       JMZ.F  $    -1, @    -1     
       JMN.F  $     0, <    -2     
       JMP.B  $    -5, >    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  >     5, >   -10     
       DJN.B  $    -1, #     6     
       NOP.F  $     0, $     0     
       NOP.F  $     0, $     0     
       MOV.I  $     2, $   -44     
       JMP.B  <   -15, $     7     
       DAT.F  <     1, $    12     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     2, $     6     
       DAT.F  $     1, $     6     
       SPL.B  #     1, $     6     
       ADD.AB #  1141, $    -3     
       MOV.I  *    -4, >    -4     
       JMP.B  $    -2, >    -5     
       END
