       ORG         67
       MOV.I  <    20, <     8     
       MOV.I  <    19, <     7     
       MOV.I  <    18, <     6     
       MOV.I  <    17, <     5     
       MOV.I  <    16, <     4     
       MOV.I  <    15, <     3     
       MOV.I  <    14, <     2     
       MOV.I  <    13, <     1     
       SPL.B  $ -3386, $ -3378     
       MOV.I  <    11, <    -1     
       DAT.F  #     0, #     0     
       ADD.AB #  1666, @     2     
       JMZ.B  $    -1, @     2     
       MOV.I  $     5, @     1     
       MOV.I  $     2, <  1664     
       JMN.B  $    -4, @    -4     
       SPL.B  $     0, <     0     
       MOV.I  $     2, <    -9     
       JMP.B  $    -1, $     0     
       DAT.F  <    -2, <   -92     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       SPL.B  $    -5, $     1     
       SPL.B  $    -6, $     0     
       SPL.B  $     0, $     1     
       SPL.B  $    -1, $     0     
       SPL.B  $    -2, $     1     
       SPL.B  $    -3, $     0     
       SPL.B  $    -4, $     1     
       SPL.B  $    -5, $     0     
       SPL.B  $    -6, $     1     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       SPL.B  $    -5, $     1     
       SPL.B  $    -6, $     0     
       SPL.B  $     0, $     1     
       SPL.B  $    -1, $     0     
       SPL.B  $    -2, $     1     
       SPL.B  $    -3, $     0     
       SPL.B  $    -4, $     1     
       SPL.B  $    -5, $     0     
       SPL.B  $    -6, $     1     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       SPL.B  $    -5, $     1     
       SPL.B  $    -6, $     0     
       SPL.B  $     0, $     1     
       SPL.B  $    -1, $     0     
       SPL.B  $    -2, $     1     
       SPL.B  $    -3, $     0     
       SPL.B  $    -4, $     1     
       SPL.B  $    -5, $     0     
       SPL.B  $    -6, $     1     
       SPL.B  $     0, $     0     
       SPL.B  $    -1, $     1     
       SPL.B  $    -2, $     0     
       SPL.B  $    -3, $     1     
       SPL.B  $    -4, $     0     
       CMP.I  $ -3264, $   582     
       JMP.B  $    23, <   873     
       CMP.I  $ -2393, $  1453     
       JMP.B  $    20, <  1164     
       CMP.I  $ -2686, $  1160     
       DJN.B  $    18, #    -4     
       CMP.I  $  2902, $  -944     
       DJN.B  $    15, #    -4     
       CMP.I  $ -1235, $  2611     
       JMP.B  $    13, <  1746     
       CMP.I  $ -2110, $  1736     
       JMP.B  $    11, <    12     
       CMP.I  $ -1530, $  2316     
       JMP.B  $     9, <    -8     
       CMP.I  $  3187, $  -659     
       JMP.B  $     6, <     7     
       CMP.I  $ -2786, $  1368     
       DJN.B  $     4, #    -8     
       CMP.I  $ -3944, $   210     
       JMP.B  $     2, <   -14     
       JMZ.B  $   -87, $ -3655     
       ADD.F  @    -4, $     7     
       ADD.F  @   -15, @    -1     
       ADD.F  @   -18, @    -2     
       CMP.I  @     4, $   -92     
       CMP.I  @     0, $     0     
       ADD.AB # -3846, $     2     
       MOV.I  $     5, @     1     
       MOV.I  $     4, <   554     
       ADD.AB #    11, @    -2     
       DJN.B  $    -3, #    11     
       JMP.B  $   -98, $     0     
       DAT.F  <    37, <   -37     
       END
