       ORG         33
       ADD.F  #     8, $     8     
       SNE.I  *     7, @     7     
       DJN.F  $    -2, @     6     
       DJN.F  $     7, $     5     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $    94, $    98     
       DAT.F  $    10, $    10     
       SPL.B  #    20, $  -200     
       MOV.I  $    -1, }    -3     
       MOV.I  $    -2, >    -4     
       DJN.A  $    -2, <    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DIV.AB #    10, #    -1     
       SLT.AB #   200, $    -1     
       JMP.B  $    19, >    -2     
       LDP.A  #     0, $    15     
       LDP.A  #   256, $     3     
       MOD.BA *    13, $     2     
       STP.B  *     1, #   256     
       JMP.B  }     0, $   226     
       DAT.F  $    55, $   650     
       DAT.F  $    54, $   101     
       DAT.F  $    35, $   886     
       DAT.F  $    34, $   653     
       DAT.F  $    33, $   104     
       DAT.F  $     8, $   889     
       DAT.F  $     7, $   656     
       DAT.F  $     6, $   107     
       DAT.F  $     9, $   630     
       DAT.F  $    46, $   226     
       DAT.F  $     0, $    10     
       DAT.F  $     1, $     9     
       DAT.F  $     1, $    11     
       MUL.AB #     5, $   -21     
       ADD.B  $   -22, $   -47     
       ADD.B  $   -23, $   -47     
       JMP.B  $   -56, $     0     
       MUL.AB #     5, $   -25     
       ADD.BA $   -26, $    10     
       DIV.AB #   400, $   -27     
       MUL.B  $   -28, $     9     
       MUL.B  $   -29, $    10     
       MUL.B  $   -30, $    11     
       MUL.B  $   -31, $    13     
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       MOV.I  {     2, {     1     
       JMP.B  $     8, {  -293     
       SPL.B  @     8, <   251     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <    26     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <   468     
       MOV.I  }    -1, >    -1     
       MOV.I  #     1, <     1     
       DJN.B  $    -2, <   323     
       MOV.I  {     4, {     3     
       MOV.I  {     3, {     2     
       DJN.B  $    -2, #     6     
       DJN.F  $   204, <  -179     
       STP.AB #    12, #   590     
       MOV.X  *     4, @     4     
       MOV.I  $    -2, }   151     
       MOV.I  $     7, }   150     
       MOV.I  $     7, }   149     
       SNE.X  $   -50, $    50     
       JMP.B  $    -4, $     0     
       MOV.I  }    -7, @    -7     
       JMN.F  $    -1, >    -8     
       JMP.B  $   582, {   536     
       STP.AB #    12, #    34     
       MOD.F  $     3, $     3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, $     0     
       MOV.I  $     2, >  -103     
       DJN.F  $    -1, >  -104     
       DAT.F  >     1, $   107     
       END
