       ORG          3
       SPL.B  $     0, <    -2     
       MOV.I  $    -3, <    -3     
       DJN.B  $    -2, <    -4     
       SPL.B  $    30, <   600     
       SPL.B  $    20, <  1100     
       SPL.B  $    10, <  1600     
       SPL.B  $     5, <  2100     
       MOV.I  $    -5, <     3     
       MOV.I  $    -7, <     2     
       MOV.I  $    -9, <     1     
       JMP.B  @     0, #  -500     
       MOV.I  $    -9, <     3     
       MOV.I  $   -11, <     2     
       MOV.I  $   -13, <     1     
       JMP.B  @     0, # -1500     
       SPL.B  $     5, <  2600     
       MOV.I  $   -14, <     3     
       MOV.I  $   -16, <     2     
       MOV.I  $   -18, <     1     
       JMP.B  @     0, #   -50     
       MOV.I  $   -18, <     3     
       MOV.I  $   -20, <     2     
       MOV.I  $   -22, <     1     
       JMP.B  @     0, # -2500     
       SPL.B  $     5, <  3600     
       MOV.I  $   -23, <     3     
       MOV.I  $   -25, <     2     
       MOV.I  $   -27, <     1     
       JMP.B  @     0, # -3500     
       MOV.I  $   -27, <     3     
       MOV.I  $   -29, <     2     
       MOV.I  $   -31, <     1     
       JMP.B  @     0, #  3500     
       SPL.B  $     5, < -3900     
       MOV.I  $   -32, <     3     
       MOV.I  $   -34, <     2     
       MOV.I  $   -36, <     1     
       JMP.B  @     0, #  2500     
       MOV.I  $   -36, <     3     
       MOV.I  $   -38, <     2     
       MOV.I  $   -40, <     1     
       JMP.B  @     0, #  1500     
       END
