       ORG         56
       MOV.I  $     3, <   -10     
       JMP.B  $    -1, < -2835     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, < -1010     
       JMP.B  $    -1, < -2994     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, < -2010     
       JMP.B  $    -1, < -3153     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, < -3010     
       JMP.B  $    -1, < -3312     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, <  3990     
       JMP.B  $    -1, < -3471     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, <  2990     
       JMP.B  $    -1, < -3630     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, <  1990     
       JMP.B  $    -1, < -3789     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $     3, <   990     
       JMP.B  $    -1, < -3948     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $   -56, <  1023     
       SPL.B  $   -50, <  2023     
       SPL.B  $   -44, <  3023     
       SPL.B  $   -38, < -3977     
       SPL.B  $   -32, < -2977     
       SPL.B  $   -26, < -1977     
       SPL.B  $   -20, <  -977     
       JMP.B  $   -14, <  -243     
       END
