       ORG         75
       SPL.B  $     0, <   -10     
       JMP.B  $    -1, <   -11     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       SPL.B  $     7, < -1000     
       SPL.B  $     6, < -2000     
       SPL.B  $     5, < -3000     
       SPL.B  $     4, <  4000     
       SPL.B  $     3, <  3000     
       SPL.B  $     2, <  2000     
       SPL.B  $   -81, <  1000     
       SUB.AB #    82, $     1     
       MOV.I  $     2, $     0     
       JMP.B  $    -2, <   -94     
       END
