       ORG          3
       DAT.F  $     0, $   -39     
       DAT.F  $     2, $     0     
       DAT.F  $     0, $     0     
       LDP.AB #     0, #     0     
       SNE.B  $    -1, #    -1     
       JMP.B  $    26, $     0     
       SNE.B  $    -3, #     0     
       JMP.B  $    12, $     0     
       STP.AB #     1, #     1     
       JMZ.B  $     0, $    -7     
       SNE.B  $    -8, #     1     
       JMP.B  $    23, $     0     
       SNE.B  $   -10, #     2     
       JMP.B  $    11, $     0     
       SNE.B  $   -12, #     3     
       JMP.B  $    16, $     0     
       MOV.I  $    22, $   -14     
       JMP.B  $     2, $     0     
       JMP.B  $    -9, $     0     
       LDP.AB #     1, #     0     
       ADD.AB #     1, $    -1     
       STP.B  $    -2, #     1     
       SLT.B  #    10, $    -3     
       JMP.B  $   -14, $     0     
       MOV.B  $   -24, $     2     
       MOV.I  $    13, >    14     
       DJN.B  $    -1, #     0     
       MOV.AB #     1, $    12     
       MOV.I  $     9, $   -28     
       MOV.I  $     9, $   -27     
       JMP.B  $   -21, $     0     
       STP.AB #     0, #     1     
       MOV.I  $     6, $   -30     
       JMP.B  $   -24, $     0     
       SPL.B  *   -32, $     0     
       MOV.I  $     3, $   -33     
       JMP.B  $   -27, $     0     
       DAT.F  $     0, $   -39     
       DAT.F  $     0, $     0     
       DAT.F  $     1, $     1     
       END
