       ORG          0
       LDP.AB >     4, #     0     
       JMN.B  $  -147, $    -1     
       LDP.AB #     0, #     0     
       SNE.AB #    -1, $    -1     
       JMP.B  $    15, #   378     
       JMZ.B  $     6, $    -3     
       STP.AB #     0, #   380     
       STP.AB #     1, #   379     
       LDP.AB #   380, #     0     
       JMZ.B  >     7, $    -1     
       JMP.B  #  -156, $     0     
       STP.AB #     0, #   379     
       STP.AB #     1, #   380     
       LDP.AB #   379, #     0     
       JMZ.B  >     2, $    -1     
       DAT.F  #     0, #     0     
       STP.A  #     1, @     0     
       JMP.B  *    -7, *    -2     
       NOP.F  #     2, }     0     
       SEQ.I  $    -2, }    -1     
       JMP.B  $    -2, }    -2     
       SNE.I  $    -3, }    -3     
       JMP.B  $     0, }    -4     
       MOV.I  $     0, $    -6     
       DAT.F  {    70, <    70     
       SPL.B  $     1, <  -200     
       MOV.I  $    -1, $     0     
       SPL.B  $     1, <  -400     
       MOV.I  <     1, {     1     
       SPL.B  $  2000, $     7     
       SPL.B  @     0, }  2268     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, } -2121     
       MOV.I  }    -1, >    -1     
       MOV.I  {    -2, <     1     
       JMP.B  @     0, >   -99     
       MOV.I  <  -182, {  -180     
       MOV.I  <  -180, {  -178     
       MOV.I  <  -178, {  -176     
       MOV.I  <  -176, {  -174     
       MOV.I  <  -174, {  -172     
       MOV.I  <  -172, {  -170     
       MOV.I  <  -170, {  -168     
       MOV.I  <  -168, {  -166     
       MOV.I  <  -166, {  -164     
       MOV.I  <  -164, {  -162     
       MOV.I  <  -162, {  -160     
       MOV.I  <  -160, {  -158     
       MOV.I  <  -158, {  -156     
       MOV.I  <  -156, {  -154     
       MOV.I  <  -154, {  -152     
       MOV.I  <  -152, {  -150     
       MOV.I  <  -150, {  -148     
       JMP.B  $    14, $     0     
       SPL.B  #     0, #     7     
       MOV.I  $    -1, >    -5     
       MOV.I  $    -2, >    -6     
       MOV.I  $    -3, >    -7     
       DJN.A  $    -3, $    -4     
       MOV.I  $     1, $    -5     
       DAT.F  #     0, #     3     
       MOV.I  $     6, $   -30     
       STP.B  $    -2, #     1     
       MOV.I  $    47, @     4     
       MOV.BA $     3, $     3     
       SUB.A  #    35, $     2     
       ADD.F  $   -42, $     1     
       SNE.I  $   133, $   168     
       ADD.F  $   -44, $    -1     
       SNE.I  *    -2, @    -2     
       ADD.F  $   -46, $    -3     
       SNE.I  *    -4, @    -4     
       DJN.B  $    -6, #    36     
       JMZ.B  $   -48, $    -1     
       SNE.I  $    36, @    -7     
       MOV.X  $    -8, $    -8     
       MOV.I  $    -9, $    31     
       JMN.F  $   -14, @    30     
       JMN.F  $     0, >   -11     
       SUB.AB #     7, $   -12     
       SNE.I  @   -13, $   -19     
       SUB.AB #    11, $   -14     
       SEQ.I  @   -15, $   -20     
       JMP.B  $   -20, $     0     
       SUB.AB #    12, $   -17     
       SUB.BA $   -18, $     3     
       MOV.I  $     2, @   -19     
       JMP.B  $   -62, $     0     
       JMP.B  $    23, $     0     
       JMP.B  $ -2729, $     0     
       MOV.I  $    -1, $   -65     
       MOV.I  $   -31, $ -2793     
       MOV.I  {    -1, <    -1     
       MOV.I  {    -2, <    -2     
       MOV.I  {    -3, <    -3     
       SPL.B  @    -4, $     0     
       MOV.I  {    -5, <    -5     
       MOV.I  {    -6, <    -6     
       MOV.I  {    -7, <    -7     
       MOV.I  $    11, $    -8     
       PIN        191
       END
