       ORG          0
       MOV.I  >    43, >     1     
       JMP.B  $    -1, #   -42     
       DAT.F  #     7, #     7     
       DAT.F  #    10, #    10     
       DAT.F  #     3, #     1     
       DAT.F  #     5, #     4     
       DAT.F  #    77, #    19     
       DAT.F  #    77, #   -19     
       DAT.F  #     0, #     3     
       DAT.F  #    77, #     0     
       MUL.AB # -3779, # -1801     
       SLT.AB # -3440, $    -1     
       JMP.B  $    18, >    -2     
       JMN.F  $     1, @    -3     
       SLT.AB # -3278, $    -4     
       JMP.B  $    10, >    -5     
       MOV.A  #    24, $    16     
       SLT.AB # -1639, $    -7     
       JMP.B  $    16, >    -8     
       MOV.X  #    77, #     0     
       MUL.F  $   -16, $    -1     
       DIV.F  $   -16, $    -2     
       MUL.A  #    -1, $    -3     
       ADD.F  $   -16, $    -4     
       JMP.B  $    15, >   -14     
       MOV.A  #    24, $     7     
       MUL.F  $   -18, $    -7     
       DIV.F  $   -24, $    -8     
       ADD.F  $   -19, $    -9     
       JMP.B  $    10, $     0     
       MUL.F  $   -28, $   -11     
       DIV.F  $   -28, $   -12     
       ADD.A  #    24, $   -13     
       JMP.B  $     6, {    -1     
       MOV.X  $   -15, $   -15     
       MUL.F  $   -31, $   -16     
       DIV.F  $   -31, $   -17     
       MUL.AB #    -1, $   -18     
       ADD.F  $   -32, $   -19     
       JMZ.B  $   -14, $   -20     
       MOV.B  $   -21, $     3     
       MUL.AB #   154, $     2     
       ADD.AB $   -23, $     1     
       DJN.B  $   -33, >   -41     
       END
