       ORG         35
       MOV.AB #  2085, $     7     
       MOV.AB #    13, $    13     
       MOV.AB #    13, $    10     
       JMZ.A  $     9, >     4     
       SUB.AB #   160, $     3     
       MOV.AB #     3, $     5     
       MOV.AB #     3, $     2     
       NOP.F  >     0, >     0     
       DJN.B  $    -1, #     0     
       ADD.AB #   155, $    -2     
       DJN.B  $    -4, #     0     
       SUB.AB #   314, $    -4     
       DJN.B  $    -9, #     0     
       ADD.AB #   145, $    -6     
       DJN.B  $   -12, #     0     
       MOV.AB #  2073, $     4     
       MOV.AB #    13, $    15     
       MOV.AB #    13, $    12     
       MOV.AB #     0, $     4     
       JMZ.A  $     2, $     0     
       SEQ.AB #     4, @    -1     
       SNE.AB #     3, @    -2     
       MOV.AB #     1, #     0     
       JMN.B  $     3, $    -1     
       MOV.I  $     9, @    -5     
       JMP.A  $     3, $     0     
       MOV.I  $     8, @    -7     
       SUB.BA $    -8, @    -8     
       SPL.A  >    -9, $     0     
       DJN.B  $   -11, #     0     
       ADD.AB #   145, $   -11     
       DJN.B  $   -14, #     0     
       JMP.A  $   -32, $     0     
       DAT.F  $     0, $     0     
       JMP.A  $  2071, $     0     
       MOV.I  $    -1, $  2058     
       MOV.I  $    -2, $  2216     
       MOV.I  $    -3, $  2371     
       MOV.I  $    -4, $  2371     
       MOV.I  $    -5, $  2371     
       JMP.A  $   -40, $     0     
       END
