       ORG         15
       MOV.I  $    55, }    55     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #   -54, $     1     
       SUB.AB #   108, $     1     
       MOV.I  $    -2, *  2719     
       MOV.I  $    -6, @    -1     
       JMZ.B  $    -3, #     0     
       MOV.I  *     6, >    -8     
       DJN.F  $    -1, >    -9     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  #     1, $    19     
       STP.AB >     0, #    14     
       MOV.I  {    14, {    12     
       MOV.I  {    13, {    11     
       MOV.I  <    12, <    10     
       MOV.I  <    11, <     9     
       MOV.I  <    10, <     8     
       MOV.I  <     9, <     7     
       MOV.I  <     8, <     6     
       MOV.I  <     7, <     5     
       MOV.I  <     6, <     4     
       MOV.I  <     5, <     3     
       MOV.I  $   -25, @     3     
       SPL.B  @     1, >  1000     
       DIV.F  # -3792, # -3796     
       DIV.F  #     0, # -3808     
       DAT.F  #   -14, #   -18     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     1, $    -1     
       SPL.B  #     2, $    -2     
       SPL.B  #     3, $    -3     
       SPL.B  #     4, $    -4     
       SPL.B  #     5, $    -5     
       SPL.B  #     6, $    -6     
       SPL.B  #     7, $    -7     
       SPL.B  #     8, $    -8     
       SPL.B  #     9, $    -9     
       SPL.B  #    10, $   -10     
       END
