       ORG          0
       LDP.AB #   182, $     3     
       LDP.A  #     0, $     2     
       MOD.AB #     2, @    -2     
       SNE.A  >     0, $     0     
       STP.BA $    -1, $    -4     
       DJN.B  $    39, @    -5     
       MOV.I  $    22, @    10     
       MOV.I  $    20, <     9     
       MOV.I  $    18, <     8     
       MOV.I  $    16, <     7     
       MOV.I  $    14, <     6     
       MOV.I  $    12, <     5     
       MOV.I  $    10, <     4     
       MOV.I  $     8, <     3     
       MOV.I  $     6, <     2     
       SPL.B  @     1, }   999     
       MOV.AB #   250, @ -3997     
       MOV.I  $     2, <    -1     
       DIV.F  #     0, $    -2     
       SPL.B  #     1, {     1     
       MOV.I  $    -1, <    -6     
       MOV.I  >    -7, >    -7     
       JMN.F  $    -2, >    -8     
       ADD.AB #    10, @    -2     
       JMZ.F  $    -1, <   -10     
       SLT.B  @    -4, #    17     
       DJN.B  $    -6, @    -5     
       DJN.B  $    -4, #    16     
       JMP.B  $    -5, {    -8     
       SPL.B  #   100, >     1     
       SPL.B  #   200, >     1     
       SPL.B  #   300, >     1     
       SPL.B  #   400, >     1     
       SPL.B  #   500, >     1     
       SPL.B  #   600, >     1     
       SPL.B  #   700, >     1     
       SPL.B  #   800, >     1     
       SPL.B  #   900, >     1     
       SPL.B  #  1000, >     1     
       DAT.F  $  1234, $ -2322     
       SPL.B  #     0, $     0     
       MOV.I  $     2, >   -19     
       DJN.F  $    -1, >   -20     
       DAT.F  > -2665, >    28     
       MOV.AB #  2028, $ -2022     
       SPL.B  $ -2005, }   666     
       MOV.I  $    -6, }    -1     
       MOV.I  $    -6, }    -2     
       MOV.I  $    -6, }    -3     
       MOV.I  $    -6, }    -4     
       END
