       ORG         42
       DAT.F  $     0, $    20     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  #   -16, $    13     
       DAT.F  # -2683, $    15     
       SPL.B  #   -18, $    15     
       SPL.B  #   -25, >   -25     
       MOV.I  @     2, >   -10     
       MOV.I  @     1, >   -11     
       DJN.B  $    -2, {    -4     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SUB.F  $   -16, $     2     
       MOV.I  $    15, *     1     
       SNE.I  * -3880, $   100     
       DJN.F  $    -3, < -2689     
       ADD.B  $    -2, $   -29     
       JMP.B  $   -21, >  3000     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $  3990, $     1     
       MOV.I  {  3748, <  3750     
       MOV.I  {  3750, <  3752     
       MOV.I  {  3752, <  3754     
       MOV.I  {  3754, <  3756     
       DJN.F  $   -20, {  3743     
       JMP.B  $   -21, {  3738     
       END
