       ORG         29
       MOV.I  <     5, {     4     
       MOV.I  <     4, {     3     
       MOV.I  <     3, {     2     
       DJN.B  $    -3, #     3     
       JMP.B  $ -2391, {     0     
       MOV.B  $     2, #     9     
       MOV.I  $     4, >    -1     
       ADD.AB #  2891, # -2219     
       JMZ.F  $    -2, @    -1     
       JMN.B  $    -4, *    -4     
       SPL.B  $     0, $     0     
       MOV.I  $     2, >    -9     
       DJN.F  $    -1, >   -10     
       DAT.F  $     0, $    13     
       SPL.B  $     1, >  -250     
       MOV.I  $     1, #     0     
       SPL.B  $     1, {  -264     
       SPL.B  @     0, < -3504     
       MOV.I  }    -1, >    -1     
       MOV.I  $     3, >    -2     
       MOV.I  {    -3, {     1     
       JMZ.A  $  1283, *     0     
       DAT.F  $     1, $     1     
       LDP.BA $     4, $     5     
       LDP.AB #     0, $    -1     
       ADD.BA @    -2, $     3     
       MOD.A  #     2, *     0     
       STP.AB {     1, #   -13     
       JMP.B  @     0, $   -28     
       SEQ.I  $   300, $   350     
       ADD.F  $    -1, $    13     
       SEQ.I  $   448, $   498     
       ADD.F  $    -1, $    11     
       SEQ.I  $   596, $   646     
       ADD.F  $    -1, $     9     
       SEQ.I  $   744, $   794     
       ADD.F  $    -1, $     7     
       SEQ.I  $   892, $   942     
       ADD.F  $    -1, $     5     
       SEQ.I  $  1040, $  1090     
       ADD.F  $    -1, $     3     
       SEQ.I  $  1188, $  1238     
       ADD.F  $    -1, $     1     
       JMZ.B  $   -20, #     0     
       MOV.I  $     5, {    -1     
       MOV.I  $     4, @    -2     
       ADD.F  $     3, $    -3     
       DJN.B  $    -3, #     9     
       JMP.B  $   -48, $     0     
       DAT.F  #    12, #   -11     
       END
