;redcode-94
;name MC#4 sol1
;author Neogryzor
;assert CORESIZE==8000
;strategy	0.8c scanner, (jmp# bombing)

;	***** SCORE: 58.8% 3-WAY TIES *****

	STEP EQU 5
	D1 EQU SREF
	D2 EQU SREF+STEP
	LOC EQU BOOT+2000-10

BOOT:	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	MOV <BPTR,{BPTR
	DJN BOOT,#2
BPTR:	JMP LOC,INC+1

SCAN:	ADD.F BMB,PTR		;14 ins
	SNE.I *PTR,@PTR
	ADD.F BMB,PTR
	SNE.I *PTR,@PTR
SREF	JMN SCAN,PTR	;<-hit
ATK:	MOV BMB,}PTR
	MOV BMB,>PTR
	MOV BMB,*PTR
	MOV BMB,@PTR
	ADD.F INC,PTR
	JMP SCAN+1
PTR:	JMP #D1,D2
BMB:	JMP #2*STEP,2*STEP
INC:	JMP #2000-1,2000-1

I FOR (MAXLENGTH-CURLINE)	;DECOY
	JMP #I,2*I
ROF

	END BOOT
