       ORG         62
       SPL.B  #     0, #  1045     
       SPL.B  #    11, #   508     
       SPL.B  #    19, #   511     
       SPL.B  #    30, #   624     
       SPL.B  #    41, #   894     
       SPL.B  #     0, #    12     
       SPL.B  #     0, #    11     
       SPL.B  #     0, #    13     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     2, >  -602     
       SPL.B  $     1, > -2517     
       SPL.B  $     1, > -1277     
       SPL.B  @     0, >  2333     
       MOV.I  }    -1, >    -1     
       MOV.I  {    -2, <     1     
       SPL.B  @     0, >  1737     
       MOV.I  # -3334, } -2333     
       DAT.F  $     1, $     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, < -2721     
       MOV.I  $     4, {  -162     
       MOV.I  $     3, @    -1     
       SUB.AB #    81, $    -2     
       DJN.F  $    -3, < -2725     
       DAT.F  < -2722, >     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       NOP.F  $     0, $ -3000     
       MOV.I  $     7, >    -1     
       ADD.AB # -2620, # -2620     
       JMZ.F  $    -2, <    -1     
       SLT.B  $    -2, #    14     
       MOV.B  $    -3, $    -5     
       JMN.B  $    -5, $    -4     
       JMP.B  $    -6, }    -6     
       SPL.B  #     0, {     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     1, $   -47     
       ADD.AB #  2394, $     1     
       MOV.I  $     6, > -2930     
       MOV.I  $    -3, @    -1     
       JMZ.B  $    -3, #     0     
       MOV.I  $     2, >    -8     
       DJN.F  $    -1, >    -9     
       DAT.F  <  2667, $    12     
       MOV.I  $    47, >    47     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #    -1, $    11     
       MOV.I  *     7, >    -4     
       MOV.I  *     6, >    -5     
       DJN.F  $    -1, {    -6     
       JMP.B  $    -2, < -2674     
       DAT.F  #     0, $    10     
       DAT.F  < -2666, <  2667     
       SPL.B  #    -2, $    11     
       SPL.B  #    -8, $    11     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  #     0, $   -57     
       LDP.A  #   321, $   -63     
       MOD.BA *   -59, $   -64     
       STP.B  *   -65, #   321     
       MOV.I  #     0, $    -1     
       ADD.AB *   -67, $    11     
       MOV.I  <    10, {    10     
       MOV.I  <     9, {     9     
       MOV.I  <     8, {     8     
       MOV.I  <     7, {     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       MOV.I  <     1, {     1     
       DJN.F  *  1430, #   -58     
       END
