       ORG          0
       LDP.A  #     0, $    13     
       LDP.A  #   400, $     3     
       MOD.BA *    11, $     2     
       STP.B  *     1, #   400     
       JMP.B  }     0, $   891     
       DAT.F  #    29, $   342     
       DAT.F  #    28, $   343     
       DAT.F  #    27, $   784     
       DAT.F  #    26, $   587     
       DAT.F  #    24, $   896     
       DAT.F  #    23, $   347     
       DAT.F  #    22, $   348     
       DAT.F  #    21, $   843     
       SPL.B  #     0, $    10     
       SPL.B  #     0, $     9     
       JMP.B  $    -6, $    11     
       JMP.B  $     7, $    -1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       ADD.F  $     5, $    -3     
       SNE.I  *    -4, @    -4     
       ADD.F  $     3, $    -5     
       SNE.I  *    -6, @    -6     
       DJN.F  $    -4, < -1007     
       SPL.B  #    13, #    13     
       MOV.I  $     2, >    -9     
       DJN.F  $    -1, >   -10     
       DAT.F  < -2665, $    13     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       JMP.B  $  1200, $    -9     
       MOV.I  $    -1, $     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       DJN.B  $    -5, #     3     
       JMP.B  $  2401, $    16     
       JMP.B  $     9, $    36     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $    10, <    -4     
       MOV.I  >    -5, >    -5     
       JMN.F  $    -2, >    -6     
       MOV.I  *    -3, <    -7     
       ADD.AB #     9, @    -3     
       JMZ.F  $    -1, @    -9     
       SLT.B  @    -5, #    18     
       JMP.B  $    -7, <   -11     
       DJN.B  $    -4, #    10     
       JMP.B  $    -5, }    -9     
       SPL.B  #     1, {     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       END
