       ORG         63
       SPL.B  #     0, #  1045     
       SPL.B  #    35, #   508     
       SPL.B  #    35, #  1081     
       SPL.B  #    35, #   146     
       SPL.B  #    23, #   511     
       SPL.B  #    23, #  1084     
       SPL.B  #    23, #   149     
       SPL.B  #    12, #   624     
       SPL.B  #    12, #  1087     
       SPL.B  #    12, #  1088     
       SPL.B  #    12, #   153     
       SPL.B  #     0, #  1453     
       SPL.B  #     0, #    12     
       SPL.B  #     0, #    11     
       SPL.B  #     0, #    13     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  @     0, $     1     
       SPL.B  $     1, >  1567     
       SPL.B  $     1, >  -876     
       SPL.B  @     0, } -1137     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, }  2620     
       MOV.I  }    -1, >    -1     
       MOV.I  {    -2, <     1     
       SPL.B  @     0, > -3628     
       MOV.I  #  2760, }  2620     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, $   -47     
       ADD.AB #  2394, $     1     
       MOV.I  $     6, > -2930     
       MOV.I  $    -3, @    -1     
       JMZ.B  $    -3, #     0     
       MOV.I  $     2, >    -8     
       DJN.F  $    -1, >    -9     
       DAT.F  <  2667, $    12     
       MOV.I  $    47, >    47     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     4, }     1     
       MOV.I  $    -1, {    -5     
       MOV.I  }    -6, }    -6     
       JMN.F  $    -2, }    -7     
       ADD.A  #     8, @    -1     
       JMZ.F  $    -1, {    -9     
       SLT.AB @    -3, #    16     
       JMP.B  $    -6, {   -11     
       DJN.B  $    -4, #    16     
       JMP.B  $    -5, {    -8     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, < -2721     
       MOV.I  $     7, <  -162     
       MOV.I  $     6, @    -1     
       SUB.AB #    81, $    -2     
       DJN.F  $    -3, < -2725     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  <     1, < -2722     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  #     0, $   -51     
       LDP.A  #   137, $   -64     
       MOD.BA *   -53, $   -65     
       STP.B  *   -66, #   137     
       MOV.I  #     0, $    -1     
       ADD.AB *   -68, $    11     
       MOV.I  <    10, {    10     
       MOV.I  <     9, {     9     
       MOV.I  <     8, {     8     
       MOV.I  <     7, {     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       MOV.I  <     1, {     1     
       DJN.F  *  1430, #   -52     
       END
