       ORG         35
       SPL.B  $     1, $     0     
       SPL.B  $     1, $     0     
       SPL.B  $    55, $     0     
       SPL.B  $     1, $     0     
       MOV.I  <     1, {     1     
       JMP.B  $  1319, $     9     
       SPL.B  @     0, }  3120     
       MOV.I  }    -1, >    -1     
       SPL.B  #  1143, $  2364     
       MOV.I  $     3, >     2     
       ADD.F  $    -2, $     1     
       JMP.F  $ -1142, {  2361     
       DAT.F  {     1, {     2     
       MOV.I  #  1143, *     0     
       SPL.B  #     1, {     1     
       MOV.I  $    -1, <    -6     
       MOV.I  >    -7, >    -7     
       JMN.F  $    -2, >    -8     
       ADD.AB #    10, @    -2     
       JMZ.F  $    -1, <   -10     
       SLT.B  @    -4, #    17     
       DJN.B  $    -6, @    -5     
       DJN.B  $    -4, #    15     
       JMP.B  $    -5, {    -8     
       DAT.F  $     0, $    -1     
       MOV.I  $    -2, @     7     
       MOV.I  <    -2, <     6     
       MOV.I  <    -3, <     5     
       MOV.I  <    -4, <     4     
       MOV.I  <    -5, <     3     
       DJN.B  $    -4, #     2     
       SPL.B  @     1, $     1     
       MOV.AB #   250, @ -3000     
       MOV.I  $   -19, <    -1     
       DIV.F  #     0, $    -2     
       LDP.A  #     0, $    19     
       LDP.A  # -2269, $     4     
       MOD.A  #    12, $     3     
       ADD.BA *    16, $     2     
       STP.B  *     1, # -2269     
       JMP.B  *     1, $     0     
       DAT.F  $   -16, $     0     
       DAT.F  $   -17, $     0     
       DAT.F  $   -18, $     3     
       DAT.F  $   -19, $     0     
       DAT.F  $   -20, $     0     
       DAT.F  $   -46, $     6     
       DAT.F  $   -47, $     9     
       DAT.F  $   -48, $     9     
       DAT.F  $   -24, $     0     
       DAT.F  $   -25, $     0     
       DAT.F  $   -26, $     0     
       DAT.F  $   -27, $     0     
       DAT.F  $     0, $     1     
       DAT.F  $     0, $     3     
       SPL.B  $     1, $     1     
       SPL.B  $     1, $     2     
       SPL.B  #  2667, $  2364     
       ADD.F  $    -1, $     1     
       JMP.F  $ -2667, {  2361     
       MOV.I  #  2667, *     0     
       END
