       ORG         50
       DAT.F  $     0, $    10     
       SPL.B  $     1, $     9     
       SPL.B  $     1, $    11     
       MOV.I  $    -1, $     0     
       SPL.B  @     0, <  3030     
       MOV.I  }    -1, >    -1     
       MOV.I  }    -2, >    -2     
       SPL.B  @     0, <  2365     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <   777     
       MOV.I  }    -1, >    -1     
       MOV.I  $     2, < -3029     
       JMP.B  $    -1, <   -10     
       DAT.F  <  2667, < -2666     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  #     0, $   -50     
       LDP.A  #   250, $     3     
       MOD.BA *   -52, $     2     
       STP.B  *     1, #   250     
       JMP.B  }     0, $   226     
       DAT.F  $    28, $   650     
       DAT.F  $    27, $   101     
       DAT.F  $    26, $   886     
       DAT.F  $    25, $   653     
       DAT.F  $    24, $   104     
       DAT.F  $     6, $   889     
       DAT.F  $     5, $   656     
       DAT.F  $     4, $   107     
       DAT.F  $     3, $   630     
       DAT.F  $     2, $   226     
       DAT.F  $     0, $     0     
       MOV.I  $    10, $  2288     
       MOV.I  $    10, $  2088     
       MOV.I  $    10, $  2088     
       MOV.I  $    10, $  2088     
       MOV.I  $    10, $  2088     
       MOV.I  $    10, $  2088     
       SPL.B  $  2083, {     0     
       SPL.B  $  2082, {     0     
       SPL.B  $   -73, $     0     
       JMP.B  $  2080, {     0     
       DAT.F  >    -1, >     1     
       SPL.B  #     0, #     0     
       SPL.B  #     0, < -1148     
       MOV.I  $   197, $ -1499     
       ADD.AB {     0, }     0     
       DJN.F  $    -2, < -1151     
       DAT.F  $     0, $     0     
       MOV.I  <     6, <     7     
       MOV.I  <     5, <     6     
       MOV.I  <     4, <     5     
       MOV.I  <     3, <     4     
       MOV.I  <     2, <     3     
       DJN.B  $    -4, #     2     
       JMP.B  $  3812, $    10     
       DAT.F  $     0, $  3819     
       MOV.I  $     7, >    -1     
       ADD.AB # -2620, # -2620     
       JMZ.F  $    -2, <    -1     
       SLT.B  $    -2, #    14     
       MOV.B  $    -3, $    -5     
       JMN.B  $    -5, $    -4     
       JMP.B  $    -6, }    -6     
       SPL.B  #     0, {     0     
       END
