       ORG         36
       SPL.B  $     1, <  2463     
       SPL.B  $     1, <  2456     
       SPL.B  $     1, <  2645     
       SPL.B  @     0, >   535     
       MOV.I  }    -1, >    -1     
       SPL.B  $  3875, $     0     
       MOV.I  >    -1, }    -1     
       MOV.I  $     3, >  -401     
       MOV.I  <    -3, <     1     
       DJN.F  @     0, > -2840     
       DAT.F  > -2666, >  2667     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  $     8, $ -2101     
       MOV.I  $    12, $ -2091     
       SPL.B  $     2, <  2667     
       SPL.B  $     2, <  2667     
       SPL.B  $     1, $ -2099     
       MOV.I  <     2, <    -1     
       DJN.B  @    -6, #     5     
       JMP.B  $   -43, $     6     
       SPL.B  #     0, $     0     
       MOV.I  $     9, @     2     
       ADD.AB # -1922, $     1     
       MOV.I  $     7, } -3041     
       DJN.F  $    -3, <  2813     
       DAT.F  $  3039, >     1     
       END
