       ORG          0
       LDP.AB #   248, $     3     
       LDP.A  #     0, $     2     
       MOD.AB #     2, @    -2     
       SNE.A  >     0, $     0     
       STP.BA $    -1, $    -4     
       DJN.B  $    42, @    -5     
       MOV.I  <    10, {    10     
       MOV.I  <     9, {     9     
       MOV.I  <     8, {     8     
       MOV.I  <     7, {     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       MOV.I  <     1, {     1     
       SPL.B  $ -2532, $    16     
       MUL.X  {     0, }     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #     0, {     0     
       SPL.B  #     0, < -2721     
       MOV.I  $     7, {  -162     
       MOV.I  $     6, @    -1     
       SUB.AB #    81, $    -2     
       DJN.F  $    -3, < -2725     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  < -2722, >     1     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  #    -4, $  3000     
       MOV.I  $    -1, >    -1     
       ADD.F  $     4, $     1     
       SEQ.I  }     4, $     0     
       MOV.B  $    -1, @    -3     
       DJN.B  $    -4, #   950     
       SPL.B  #  -152, >  -152     
       MOV.I  $     2, >   -12     
       DJN.F  $    -1, >   -13     
       DAT.F  $     1, #    18     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $ -1502, $    28     
       MOV.I  $   -13, $ -1543     
       MOV.I  $    -2, $   -32     
       JMP.B  $   -42, $     0     
       END
