       ORG         11
       DAT.F  $     3, $   -38     
       DAT.F  <   -15, $    20     
       DAT.F  <   -15, $    20     
       SPL.B  # -2670, $    30     
       MOV.I  @     2, >    -4     
       MOV.I  @     1, >    -5     
       DJN.B  $    -2, {    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       ADD.F  $    34, $     1     
       SNE.I  $ -2656, $ -2647     
       DJN.F  $    -2, @    -1     
       ADD.B  $    -2, $   -14     
       MOV.I  $   -12, <    -3     
       JMP.B  *     0, {     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  # -2674, # -2674     
       END
