       ORG         21
       MOV.I  {    61, $  3175     
       ADD.X  #  3174, *     1     
       JMP.B  $    -2, }    -2     
       DAT.F  $     0, $    12     
       SPL.B  *     1, $    13     
       SPL.B  *     1, $    11     
       SPL.B  $     1, }     0     
       SPL.B  $     1, >  1234     
       SPL.B  @     0, >  2359     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, >  3201     
       MOV.I  }    -1, >    -1     
       MOV.I  $     4, >  1529     
       MOV.I  $     3, >  -727     
       MOV.I  {    -4, <     1     
       DJN.B  @     0, <  2899     
       DAT.F  <  2667, < -2666     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       LDP.A  }     0, $   -18     
       LDP.A  #   333, $     3     
       MOD.BA *   -20, $     2     
       STP.B  *     1, #   333     
       JMP.B  }     0, $   651     
       SPL.B  #   -22, $   924     
       SPL.B  #   -23, $  1599     
       SPL.B  #   -24, $   871     
       SPL.B  #     6, $  1214     
       SPL.B  #     5, $  1072     
       SPL.B  #     4, $   149     
       SPL.B  #     4, $  1503     
       SPL.B  #     3, $  1075     
       JMP.B  #     2, $   152     
       MOV.AB #     2, $     4     
       MOV.I  >     3, >     4     
       MOV.I  >     2, >     3     
       MOV.I  >     1, >     2     
       JMN.A  $    -3, @   -39     
       DJN.F  *  -574, #  -576     
       MUL.X  {     5, }     6     
       SLT.BA #    11, # -1993     
       MOV.B  @     3, $    -2     
       MOV.I  $     5, >    -3     
       ADD.AB # -1993, $    -3     
       JMZ.F  $    -1, @    -4     
       JMN.B  $    -6, $    -5     
       JMP.B  $    -4, }    -4     
       SPL.B  #     0, }     0     
       END
