       ORG         38
       ADD.F  $     4, $    18     
       SNE.I  *    17, @    17     
       JMP.B  $    -2, $     0     
       JMP.B  $    17, $     0     
       DAT.F  $    10, $    10     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  {   209, >  3569     
       DAT.F  >  3370, {    10     
       SPL.B  #    20, < -2666     
       MOV.I  $    -1, >    -3     
       MOV.I  $    -2, }    -4     
       DJN.A  $    -2, <    -3     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  { -1310, < -1308     
       MOV.I  < -1310, < -1307     
       MOV.I  { -1307, < -1305     
       MOV.I  < -1305, < -1302     
       MOV.I  { -1297, < -1302     
       MOV.I  < -1302, < -1301     
       DJN.F  $   -43, < -1306     
       END
