       ORG         84
       DAT.F  $  -872, $  -872     
       JMP.I  #  2376, #     0     
       MOV.I  $    -1, *     2     
       MOV.I  $    -2, @     1     
       MOV.I  * -3243, *  -867     
       ADD.F  $  3995, $    -1     
       DJN.B  $    -4, #   332     
       JMZ.B  #     0, >   100     
       SNE.I  <    99, $ -3925     
       JMP.B  $     3, $     0     
       SEQ.I  >    97, $ -3928     
       JMP.B  $    -4, $     0     
       ADD.AB #     3, $    95     
       MOV.I  $ -3963, >    94     
       MOV.I  $ -3963, >    93     
       JMP.B  $    -8, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       JMP.B  #    -1, $     0     
       JMP.B  #     0, $     1     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     3, $     0     
       DAT.F  $     0, $   -45     
       DAT.F  $     3, $     6     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       MOV.I  $   -83, $  3917     
       JMP.B  $  3903, $     0     
       END
