       ORG         65
       DAT.F  >   -86, >   673     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SPL.B  $     2, <  1402     
       SPL.B  $     1, <  1645     
       SPL.B  $     1, <  1888     
       MOV.I  <     1, {     1     
       SPL.B  $  1090, $     7     
       SPL.B  @     0, < -3403     
       MOV.I  }    -1, >    -1     
       SPL.B  @     0, <   664     
       MOV.I  }    -1, >    -1     
       MOV.I  #     1, <     1     
       DJN.B  $    -2, # -1465     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $   -19, $ -2953     
       DAT.F  $   -20, $ -2710     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       SNE.I  $  2715, $ -3640     
       SEQ.I  <   -66, $  2251     
       JMP.B  $    25, }    25     
       SNE.I  $  -652, $   993     
       SEQ.I  <   -50, $ -1116     
       JMP.B  $    22, {    22     
       SNE.I  $  -899, $   746     
       SEQ.I  <   -54, $ -1363     
       DJN.A  $    19, {    19     
       SNE.I  $  3926, $ -2186     
       SEQ.I  <   -70, $  3704     
       JMP.B  $    16, }    18     
       SNE.I  $  3435, $ -3163     
       SEQ.I  <   -75, $  2727     
       JMP.B  $    13, {    15     
       SNE.I  $  3676, $ -2679     
       SEQ.I  <   -77, $  3211     
       JMP.B  $    10, $     0     
       SEQ.I  >    13, $  3765     
       JMP.B  $     9, <    12     
       SEQ.I  $  1259, $  2903     
       JMP.B  $     6, }     6     
       SEQ.I  $  2510, $ -3846     
       JMP.B  $     4, {     4     
       SEQ.I  $  2021, $  3665     
       DJN.A  $     2, {     2     
       JMZ.F  $   -88, $ -3155     
       MUL.B  *     2, $     4     
       SNE.I  {   -74, @     3     
       ADD.B  $   -90, $     2     
       MOV.I  $   -95, @     1     
       MOV.I  $   -96, }  2108     
       SUB.AB #    -7, $    -1     
       DJN.B  $    -3, #    19     
       DJN.F  $   -96, #     0     
       END
