       ORG         63
       JMP.B  $    18, $   100     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.BA $    -3, $    -3     
       MOV.AB #    -6, $     2     
       ADD.B  $    -5, $     1     
       MOV.X  @     0, @     0     
       MOV.B  @    -1, $    -1     
       MOV.I  $    16, <    -8     
       MOV.I  >    -9, >    -9     
       JMN.F  $    -2, >   -10     
       ADD.BA $    -5, $   -11     
       JMZ.F  $     4, *   -12     
       MOV.AB $   -13, $   -13     
       SLT.B  $   -14, #    32     
       JMN.F  $    -7, @   -15     
       MOD.AB #  9230, $   -16     
       ADD.AB #    13, $   -17     
       JMZ.F  $    -1, @   -18     
       MOD.AB #  9230, $   -19     
       SLT.B  $   -20, #    37     
       JMZ.F  $   -18, $   -20     
       DJN.B  $    -5, #     9     
       SPL.B  #     0, #     0     
       SPL.B  #     0, #     0     
       MOV.I  $     4, <    -2     
       MOV.I  $     3, >    -5     
       MOV.I  $     2, >    -6     
       DJN.F  $    -2, >    -7     
       DAT.F  $     0, $    10     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       DAT.F  $     0, $     0     
       MOV.I  <    30, {    30     
       MOV.I  <    29, {    29     
       MOV.I  <    28, {    28     
       MOV.I  <    27, {    27     
       MOV.I  <    26, {    26     
       MOV.I  <    25, {    25     
       MOV.I  <    24, {    24     
       MOV.I  <    23, {    23     
       MOV.I  <    22, {    22     
       MOV.I  <    21, {    21     
       MOV.I  <    20, {    20     
       MOV.I  <    19, {    19     
       MOV.I  <    18, {    18     
       MOV.I  <    17, {    17     
       MOV.I  <    16, {    16     
       MOV.I  <    15, {    15     
       MOV.I  <    14, {    14     
       MOV.I  <    13, {    13     
       MOV.I  <    12, {    12     
       MOV.I  <    11, {    11     
       MOV.I  <    10, {    10     
       MOV.I  <     9, {     9     
       MOV.I  <     8, {     8     
       MOV.I  <     7, {     7     
       MOV.I  <     6, {     6     
       MOV.I  <     5, {     5     
       MOV.I  <     4, {     4     
       MOV.I  <     3, {     3     
       MOV.I  <     2, {     2     
       MOV.I  <     1, {     1     
       SPL.B  $  9177, $   -63     
       ADD.F  $     3, $    -1     
       DJN.B  $   -32, #     5     
       JMP.B  $   -78, $   100     
       DAT.F  $  9270, $    30     
       END
