.PHONY: test test_round3 test_round6 test_round7

test: test_round3 test_round6 test_round7

test_round3:
	$(MAKE) -C round3 test

test_round6:
	$(MAKE) -C round6 test

test_round7:
	$(MAKE) -C round7 test
