       ORG          9
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       MOV.I  $    -1, <    -3     
       SPL.B  $     0, <    -2     
       MOV.I  $    -3, <    -3     
       DJN.B  $    -2, <    -4     
       SPL.B  $    40, <   600     
       SPL.B  $    20, <  1100     
       SPL.B  $    10, <  1600     
       SPL.B  $     5, <  2100     
       MOV.I  $    -5, <     3     
       MOV.I  $    -7, <     2     
       MOV.I  $    -9, <     1     
       JMP.B  @     0, #  -500     
       MOV.I  $    -9, <     3     
       MOV.I  $   -11, <     2     
       MOV.I  $   -13, <     1     
       JMP.B  @     0, # -1000     
       SPL.B  $     5, <  2600     
       MOV.I  $   -14, <     3     
       MOV.I  $   -16, <     2     
       MOV.I  $   -18, <     1     
       JMP.B  @     0, #   -50     
       MOV.I  $   -18, <     3     
       MOV.I  $   -20, <     2     
       MOV.I  $   -22, <     1     
       JMP.B  @     0, # -1500     
       SPL.B  $    10, <  3100     
       SPL.B  $     5, <  3600     
       MOV.I  $   -24, <     3     
       MOV.I  $   -26, <     2     
       MOV.I  $   -28, <     1     
       JMP.B  @     0, # -2000     
       MOV.I  $   -28, <     3     
       MOV.I  $   -30, <     2     
       MOV.I  $   -32, <     1     
       JMP.B  @     0, # -2500     
       SPL.B  $     5, < -3900     
       MOV.I  $   -33, <     3     
       MOV.I  $   -35, <     2     
       MOV.I  $   -37, <     1     
       JMP.B  @     0, # -3000     
       MOV.I  $   -37, <     3     
       MOV.I  $   -39, <     2     
       MOV.I  $   -41, <     1     
       JMP.B  @     0, # -3500     
       SPL.B  $    20, < -3400     
       SPL.B  $    10, < -2900     
       SPL.B  $     5, < -2400     
       MOV.I  $   -44, <     3     
       MOV.I  $   -46, <     2     
       MOV.I  $   -48, <     1     
       JMP.B  @     0, #  4000     
       MOV.I  $   -48, <     3     
       MOV.I  $   -50, <     2     
       MOV.I  $   -52, <     1     
       JMP.B  @     0, #  3500     
       SPL.B  $     5, < -1900     
       MOV.I  $   -53, <     3     
       MOV.I  $   -55, <     2     
       MOV.I  $   -57, <     1     
       JMP.B  @     0, #  3000     
       MOV.I  $   -57, <     3     
       MOV.I  $   -59, <     2     
       MOV.I  $   -61, <     1     
       JMP.B  @     0, #  2500     
       SPL.B  $    10, < -1400     
       SPL.B  $     5, <  -900     
       MOV.I  $   -63, <     3     
       MOV.I  $   -65, <     2     
       MOV.I  $   -67, <     1     
       JMP.B  @     0, #  2000     
       MOV.I  $   -67, <     3     
       MOV.I  $   -71, <     2     
       MOV.I  $   -71, <     1     
       JMP.B  @     0, #  1600     
       SPL.B  $     5, <  -400     
       MOV.I  $   -72, <     3     
       MOV.I  $   -76, <     2     
       MOV.I  $   -76, <     1     
       JMP.B  @     0, #  1100     
       MOV.I  $   -76, <     3     
       MOV.I  $   -78, <     2     
       MOV.I  $   -80, <     1     
       JMP.B  @     0, #   500     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       DAT.F  #     0, #     0     
       END
