name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/test-tournaments.yml'
      - 'tests/tournaments/**'
      - 'warriors/tournaments/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/test-tournaments.yml'
      - 'tests/tournaments/**'
      - 'warriors/tournaments/**'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      upload-artifact: true

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pmars-Server
          path: bin/
      - name: Run test
        run: |
          chmod +x bin/pmars
          ./bin/pmars -A warriors/validate.red
