name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      upload-artifact: true

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pmars-Server
          path: bin/
      - name: Run test
        run: |
          chmod +x bin/pmars
          ./bin/pmars -A warriors/validate.red
          ./bin/pmars -A warriors/tournaments/icwt1986/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1987/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1988/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1989/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1990/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1991/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1992/*.red > /dev/null
          ./bin/pmars -A warriors/tournaments/icwt1993/*.red > /dev/null
